### ISSUE TITLE
Not enough funds to cover the tx fees for sending out payments

### ISSUE THREAD

**Issue by Elmit2015** [zone117x/node-open-mining-portal#421]
I know, it was asked several times before, but I cannot figure out how to solve it. 

Redis tells me a balance of 17489.xxx and my min payment is 17500, so just 10.xxx are missing to pay.

Payments were made till Dec. 30 with this coin. 

What exactly do I need to do to get this fixed?

**Comment by wmikrut** [comment]
I had this same problem and, for me, is was caused by the transaction fees incurred for sending payments on a specific coin.

Some coins have very large transaction fees.  Sending multiple payments would consume the balance and -- you will not have enough funds to cover payments with such high txn fees... regardless of how high/low you set the payout threshold.

I have removed some coins from my NOMP instance as the transaction fees required made them unsuitable for usage in NOMP.

**Comment by Elmit2015** [comment]
I think there is an error in the code, ... since some coins transfer now for a long time (several months) and suddenly this message pops up. Worse, I get more of these coins. 

How can we fix that? Payment is restarting all the time:
/home/ronald/nomp/libs/paymentProcessor.js:443
                    Object.keys(workerShares).forEach(function(worker){
                           ^
TypeError: Object.keys called on non-object
    at Function.keys (native)
    at moveSharesToCurrent (/home/ronald/nomp/libs/paymentProcessor.js:443:28)
    at /home/ronald/nomp/libs/paymentProcessor.js:457:33
    at Array.forEach (native)
    at async.waterfall.paymentProcessTime (/home/ronald/nomp/libs/paymentProcessor.js:449:24)
    at fn (/home/ronald/nomp/node_modules/async/lib/async.js:641:34)
    at Object._onImmediate (/home/ronald/nomp/node_modules/async/lib/async.js:557:34)
    at processImmediate [as _immediateCallback] (timers.js:345:15)


2015-01-13 11:52:54 [Payments]  [42] Daemon reports invalid transaction: a863f06ae9748f23d59c6ce9f80481b244b6cf558b862426fb22489124febea5
2015-01-13 11:52:54 [Payments]  [42] Daemon reports invalid transaction: 5ccc96bce2fc222e1884cae4992d05be7c34d378e33aec5a999bbc43a12b0c4c
2015-01-13 11:52:54 [Payments]  [42] Daemon reports invalid transaction: 2b667bfd1a8bcab915900e84b0dc7a9ec3060dc7c14d97619f1a4b69462414a7
2015-01-13 11:52:54 [Payments]  [42] No worker shares for round: 593415 blockHash: c91053dae3661232e7bc2b168174817747287f2ee10c2f597fc9e40e09f5d455
2015-01-13 11:52:54 [Payments]  [42] Not enough funds to cover the tx fees for sending out payments, decreasing rewards by 1% and retrying
2015-01-13 11:52:54 [Payments]  [42] Not enough funds to cover the tx fees for sending out payments, decreasing rewards by 2% and retrying
2015-01-13 11:52:54 [Payments]  [42] Not enough funds to cover the tx fees for sending out payments, decreasing rewards by 3% and retrying
2015-01-13 11:52:54 [Payments]  [42] Not enough funds to cover the tx fees for sending out payments, decreasing rewards by 4% and retrying
2015-01-13 11:52:54 [Payments]  [42] Not enough funds to cover the tx fees for sending out payments, decreasing rewards by 5% and retrying
2015-01-13 11:52:54 [Payments]  [42] Not enough funds to cover the tx fees for sending out payments, decreasing rewards by 6.000000000000001% and retrying
2015-01-13 11:52:54 [Payments]  [42] Not enough funds to cover the tx fees for sending out payments, decreasing rewards by 7.000000000000001% and retrying
2015-01-13 11:52:54 [Payments]  [42] Not enough funds to cover the tx fees for sending out payments, decreasing rewards by 8% and retrying
2015-01-13 11:52:54 [Payments]  [42] Not enough funds to cover the tx fees for sending out payments, decreasing rewards by 9% and retrying
2015-01-13 11:52:55 [Payments]  [42] Not enough funds to cover the tx fees for sending out payments, decreasing rewards by 10% and retrying
2015-01-13 11:52:55 [Payments]  [42] Not enough funds to cover the tx fees for sending out payments, decreasing rewards by 10.999999999999998% and retrying
2015-01-13 11:52:55 [Payments]  [42] Not enough funds to cover the tx fees for sending out payments, decreasing rewards by 11.999999999999998% and retrying
2015-01-13 11:52:55 [Payments]  [42] Not enough funds to cover the tx fees for sending out payments, decreasing rewards by 12.999999999999998% and retrying
2015-01-13 11:52:55 [Payments]  [42] Not enough funds to cover the tx fees for sending out payments, decreasing rewards by 13.999999999999998% and retrying
2015-01-13 11:52:55 [Payments]  [42] Not enough funds to cover the tx fees for sending out payments, decreasing rewards by 15% and retrying
2015-01-13 11:52:55 [Payments]  [42] Not enough funds to cover the tx fees for sending out payments, decreasing rewards by 16% and retrying
2015-01-13 11:52:55 [Payments]  [42] Not enough funds to cover the tx fees for sending out payments, decreasing rewards by 17% and retrying
2015-01-13 11:52:55 [Payments]  [42] Not enough funds to cover the tx fees for sending out payments, decreasing rewards by 18.000000000000004% and retrying
2015-01-13 11:52:55 [Payments]  [42] Not enough funds to cover the tx fees for sending out payments, decreasing rewards by 19.000000000000004% and retrying
2015-01-13 11:52:55 [Payments]  [42] Not enough funds to cover the tx fees for sending out payments, decreasing rewards by 20.000000000000004% and retrying
2015-01-13 11:52:55 [Payments]  [42] Not enough funds to cover the tx fees for sending out payments, decreasing rewards by 21.000000000000004% and retrying
2015-01-13 11:52:55 [Payments]  [42] Not enough funds to cover the tx fees for sending out payments, decreasing rewards by 22.000000000000007% and retrying
2015-01-13 11:52:55 [Payments]  [42] Not enough funds to cover the tx fees for sending out payments, decreasing rewards by 23.000000000000007% and retrying


As you see, it starts with invalid transactions. It seems it deducted already the amount and tries again to send, but does not have anymore the funds. 

Is it a matter fo time to get the invalid transactions cleared out, or what can I do to get it working again?

**Comment by wmikrut** [comment]
Unfortunately I was not able to resolve the issue.

What I did was stop the coin... loaded redis commander and made manual payments for those due.
I experienced this issue with CetusCoin and CashCoin.

I have not re-activated those coins in my pool.

I have 24 other coins NOMP works perfectly on... so it has to be a wallet issue with those coins.

**Comment by Elmit2015** [comment]
Still some issues:
SEEDING UPDATE FAILED

**Comment by Elmit2015** [comment]
I deleted the blog and tried another one. Same result: The Editing sign does not appear. 

At the terminal window I can see:
Site:19Wd2M..wNXd Can't update content.json

I tried:
1. to add a new blog entry (OK)
2. to change title (OK)
3. to change body (No editing sign)
4. stop ZeroNet and sign the new blog in the terminal window
5. try to change now body, same: No editing sign

The purple dot only bring me to the main, but does not offer me to sign anymore.
