### ISSUE TITLE
Migrating NOMP to new server POS coins error out

### ISSUE THREAD

**Issue by ob1100** [zone117x/node-open-mining-portal#423]
Anyone bump in to this ? It will only happen with the POS coins. Fresh install of debian or ubunto (both do the same thing. I am running on my prod on a debian server but am not having the same problem. Am I missing an undocumented dependency?

nvalid pubkey: 049514a4ef8ec1fd7010bb6559ccb1276be17bfe7386bfe3eed79dc6e0ddfe7161784a52a623a8beec2649bae2e0116af026f12c3a88120a37a5

/home/nomp/node_modules/stratum-pool/lib/util.js:246
        throw new Error();
              ^
Error
    at Object.exports.pubkeyToScript (/home/nomp/node_modules/stratum-pool/lib/util.js:246:15)
    at /home/nomp/node_modules/stratum-pool/lib/pool.js:419:37
    at /home/nomp/node_modules/stratum-pool/lib/pool.js:423:15
    at /home/nomp/node_modules/stratum-pool/lib/daemon.js:134:13
    at parseJson (/home/nomp/node_modules/stratum-pool/lib/daemon.js:85:17)
    at IncomingMessage.<anonymous> (/home/nomp/node_modules/stratum-pool/lib/daemon.js:95:17)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:442:13)

Thanks

**Comment by ob1100** [comment]
I figured it out..... for some reason all the POS wallets that I importer a new address to, the new address did not work. I used the original wallet address that came with the wallet and they worked. As long as it works I guess.
