### ISSUE TITLE
can i put new coin to the pool

### ISSUE THREAD

**Issue by buana** [zone117x/node-open-mining-portal#429]
Hello , sorry if its sound noobish , but can i put new coin that not listed in your coins folder ? i tried to put manually but it become errors 
undefined:1
{"name":"garuda","symbol":"GRD","algorithm":"sha256","peerMagic":"",│·········
                                                                    ^
SyntaxError: Unexpected token │
    at Object.parse (native)
    at /root/nomp/init.js:143:32
    at Array.forEach (native)
    at buildPoolConfigs (/root/nomp/init.js:133:21)
    at init (/root/nomp/init.js:431:19)
    at Object.<anonymous> (/root/nomp/init.js:443:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

what should i do ? :) many thanks

**Comment by sysmanalex** [comment]
@buana You should just follow format of coin definition. 
Seems you make mistake. 
You may just define minimum - "name":"garuda","symbol":"GRD","algorithm":"sha256" 
. without peermagic , please check how it done in other files.

**Comment by buana** [comment]
thank you for the fast response
