### ISSUE TITLE
error starting nomp

### ISSUE THREAD

**Issue by achow101** [zone117x/node-open-mining-portal#432]
I followed the instructions in the readme and set everything up. However, when I run 
node init.js

I get the following error

module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: /root/nomp/node_modules/bignum/build/Release/bignum.node: undefined symbol: node_module_register
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at new require (module.js:380:17)
    at Object.<anonymous> (/root/nomp/node_modules/bignum/index.js:4:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

I think this is related to node.js, but I can't figure out what is wrong.

**Comment by micheldaniel** [comment]
try this

put in the folder where you have the mining pole stand this

npm install bignum

and start again

**Comment by erm3nda** [comment]
npm install bignum has failed in 4 different Windows environments and 2 Linux environments.
Always got a node-gyp configure build error for bignum. I've tested bignum@0.11.0 and a previous versions with no lucky.

**Comment by mmitech** [comment]
what node and npm version do you have ? try node 0.10.x and npm 2.x.x

**Comment by erm3nda** [comment]
My mistake, i was missing the OpenSSL-Win64 libraries, now has built it ok. But I'm facing a kidding experience installing Node modules.

**Comment by djspacedevil** [comment]
i have the same problem on CentOS

did anybody know, what the problem is?
```
module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: /opt/Pools/unomp/node_modules/bignum/build/Release/bignum.node: undefined symbol: node_module_register
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at new require (module.js:380:17)
    at Object.<anonymous> (/opt/Pools/unomp/node_modules/bignum/index.js:4:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by cibermax** [comment]
Ubuntu 16.04 

root@dgb-pool:~/nomp# node init.js
module.js:435
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module did not self-register.
    at Error (native)
    at Object.Module._extensions..node (module.js:435:18)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/nomp/node_modules/bignum/index.js:4:11)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
root@dgb-pool:~/nomp#

**Comment by micheldaniel** [comment]
try command npm update

**Comment by rahulmanuwas** [comment]
Make sure your configurations are correct and then try:
nvm install 0.10.25
nvm use 0.10.25
npm update

**Comment by 2pay** [comment]
this error node version change. You must set nodejs version return 0.10.25 `nvm use 0.10.25`. When you start website then close console this error appear again.
