### ISSUE TITLE
NPM Update Fails on Installation

### ISSUE THREAD

**Issue by AmericanComputerNerd** [zone117x/node-open-mining-portal#433]
My installation is failing after the NPM Update command.  I saw a previous issue with nodejs's latest build having issues, so I installed nodejs v.1 instead of v.12 and still getting the error.  Below is the screen output.

-----
compilation terminated.
make: *** [Release/obj.target/multihashing/sha1.o] Error 1
make: Leaving directory `/root/nomp/node_modules/stratum-pool/node_modules/multi-hashing/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.13.0-53-generic
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/nomp/node_modules/stratum-pool/node_modules/multi-hashing
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

npm ERR! multi-hashing@0.0.9 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the multi-hashing@0.0.9 install script.
npm ERR! This is most likely a problem with the multi-hashing package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls multi-hashing
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.0-53-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "update"
npm ERR! cwd /root/nomp
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

**Comment by darknetdeep** [comment]
i have the same error, when i try npm update

first problem 

npm WARN unmet dependency /root/nomp/node_modules/dateformat/node_modules/meow/node_modules/indent-string requires get-stdin@'^4.0.1' but will load
npm WARN unmet dependency /root/nomp/node_modules/dateformat/node_modules/get-stdin,
npm WARN unmet dependency which is version 5.0.0

**Comment by darknetdeep** [comment]
after fails multi-hashing with the same error

**Comment by llamadevelopment** [comment]
i have the same error as OP

**Comment by pfrankw** [comment]
Same error here

**Comment by AmericanComputerNerd** [comment]
I can help fix this error, and get your mining pools up and running.  Find me on Fiverr.com, and send me a PM.  Services start at $5, and go up depending on the level of my involvement.

https://www.fiverr.com/mmarcellus

**Comment by Fyah112** [comment]
I have the exact same issue some help or tips would be nice :)

**Comment by zakyvr** [comment]
OP. It would be helpful to show the output log preceding what you posted here.

For me the issues with multi-hashing were resolved by installing node v0.10.36 from the binary here:
https://nodejs.org/dist/v0.10.36/node-v0.10.36-linux-x64.tar.gz

**Comment by jmtibbetts** [comment]
apt-get install build-essential libtool autotools-dev autoconf pkg-config libssl-dev
apt-get install libboost-all-dev git npm nodejs nodejs-legacy libminiupnpc-dev redis-server
add-apt-repository ppa:bitcoin/bitcoin
apt-get update
apt-get install libdb4.8-dev libdb4.8++-dev
curl https://raw.githubusercontent.com/creationix/nvm/v0.16.1/install.sh | sh

***Important******
source ~/.profile
nvm install 0.10.25
nvm use 0.10.25
†***************†

That script the source and NVM install / use 0.10.25 = protip
