### ISSUE TITLE
error node init.js

### ISSUE THREAD

**Issue by lstrchm** [zone117x/node-open-mining-portal#436]
Hi,
I'm getting this error, any ideas?

/home/user/nomp/init.js:25
var portalConfig = JSON.parse(JSON.minify(fs.readFileSync("config.json", {enco
                                   ^
TypeError: Property 'minify' of object #<Object> is not a function
    at Object.<anonymous> (/home/user/nomp/init.js:25:36)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3

**Comment by lstrchm** [comment]
fixed by changing the version in package.json to "node-json-minify": ">= 0.1.3-a"
