### ISSUE TITLE
Error/Problem Node installation

### ISSUE THREAD

**Issue by zimbo123** [zone117x/node-open-mining-portal#442]
Hello,

i installed the node-open-mining-Portal on my Ubuntu 14.02. Server, but when i start the node with 
node init.js i got following message

module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at new require (module.js:384:17)
    at Object.<anonymous> (/home/coin/nomp/node_modules/bignum/index.js:4:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

Can anybody help me? I found several Solutions in Google, but nothing helped me.
Thank you very much.

Best regards 

Zimbo

**Comment by crackfoo** [comment]
Tried:

npm install bignum

already?

**Comment by zimbo123** [comment]
Thank you, i tried it and then i got following message

make: Entering directory '/home/coin/nomp/node_modules/bignum/build'
  CXX(target) Release/obj.target/bignum/bignum.o
  SOLINK_MODULE(target) Release/obj.target/bignum.node
  COPY Release/bignum.node
make: Leaving directory '/home/coin/nomp/node_modules/bignum/build'
bignum@0.11.0 node_modules/bignum
root@d10321:/home/coin/nomp# node init.js
/home/coin/nomp/node_modules/bindings/bindings.js:83
        throw e
              ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (/home/coin/nomp/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/home/coin/nomp/node_modules/stratum-pool/node_modules/multi-hashing/index.js:1:99)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
root@d10321:/home/coin/nomp#

**Comment by zimbo123** [comment]
Sorry i made i mistake is an Ubuntu 15.04

Operating system	Ubuntu Linux 15.04
Webmin version	1.760
Kernel and CPU	Linux 3.19.0-28-generic on x86_64

**Comment by zimbo123** [comment]
I found the error, i edit the package.json and set "node-json-minify": ">= 0.1.3-a".
After then update with npm update
