### ISSUE TITLE
Error: Cannot find module './sequences'

### ISSUE THREAD

**Issue by heldertb** [zone117x/node-open-mining-portal#450]
Hello,

I'm getting this error when trying to start the server. I have tried to do npm install sequences but no luck.
Any ideas?

```
module.js:340
    throw err;
          ^
Error: Cannot find module './sequences'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/stratumpool/node-open-mining-portal/node_modules/mysql/lib/protocol/Protocol.js:2:20)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
2016-02-21 11:22:48 [Master]	[PoolSpawner] Fork 0 died, spawning replacement worker...

module.js:340
    throw err;
          ^
Error: Cannot find module './sequences'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/stratumpool/node-open-mining-portal/node_modules/mysql/lib/protocol/Protocol.js:2:20)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
2016-02-21 11:22:48 [Master]	[PoolSpawner] Fork 1 died, spawning replacement worker...
```

**Comment by heldertb** [comment]
Okay, I fixed it somehow.
did: sudo npm cache clean
and installed mysql again with npm install mysql

**Comment by wuhuaping** [comment]
atiger77758@163.com  我也出现这样的问题 怎么去解决它呢 拜托了
我也出现这样的问题 怎么去解决它呢  拜托了
I also have such a problem how to solve it, please

**Comment by heldertb** [comment]
@wuhuaping try to reinstall all your dependencies. As stated above:
`sudo npm cache clean`
`rm -rf node_modules`
`npm install`
