### ISSUE TITLE
Fail to run node init.js after install

### ISSUE THREAD

**Issue by volkinsonable** [zone117x/node-open-mining-portal#460]
Hi. Having problem after installing node for MPOS. 
Here is what i get:
`Error: Cannot find module 'extend'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/bitcoin/node-open-mining-portal/init.js:7:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
`
Where can be problem? Thanks for any clue how to get it started.

**Comment by volkinsonable** [comment]
got it working. `sudo npm update`
