### ISSUE TITLE
sudo node inito.js ERROR running Dashcoin 

### ISSUE THREAD

**Issue by hiroshi2701** [zone117x/node-open-mining-portal#466]
Hi guys,

Can you guys help me please? I'm having a problem when I starting my mining pool for dashcoin. Here's the error I'm getting:

[2016-09-20 11:27:48.124] [DEBUG] [default] - Pool dash Thread 2 Share processing setup with redis (127.0.0.1:6379)
[2016-09-20 11:27:57.046] [DEBUG] [default] - Master CLI CLI listening on port 17117
[2016-09-20 11:27:57.645] [INFO] [default] - New Relic
[2016-09-20 11:27:57.649] [INFO] [default] - POSIX Not Installed
[2016-09-20 11:27:57.649] [INFO] [default] - Run Workers
[2016-09-20 11:27:57.659] [INFO] [default] - New Relic
[2016-09-20 11:27:57.662] [INFO] [default] - POSIX Not Installed
[2016-09-20 11:27:57.662] [INFO] [default] - Run Workers

**[2016-09-20 11:27:57.677] [ERROR] [default]** - Payments dash Error with payment processing daemon {"type":"offline","message":"connect ECONNREFUSED"}
[2016-09-20 11:27:57.713] [DEBUG] [default] - Website Server Website started on 45.32.51.56:80
**[2016-09-20 11:27:57.780] [ERROR] [default]** - Website dash Could not dumpprivkey for dash {"type":"offline","message":"connect ECONNREFUSED"}

Any help will be appreciated! Thank you! 

Best Regards,
Mark
Sigway Higgs

**Comment by Fyah112** [comment]
is your node up?

**Comment by oelke** [comment]
Is redis ok?

**Comment by hiroshi2701** [comment]
Hi guys,

I'm so sorry for the late reply and thank you for your response. This is on uNOMP. 

I'm very newbie on this. What do you mean by node up? and redis? my website mining pool is running perfectly fine. But when I started miner to mine, I didn't get any blocks being reported found/pending/orphand. Maybe there is something wrong with my dash.json maybe? 

{
"enabled": true,
"coin": "dash.json",

"auxes": [],
"address": "[dash wallet address where]",

"rewardRecipients": {
    "n37vuNFkXfk15uFnGoVyHZ6PYQxppD3QqK": 1.5,
    "22851477d63a085dbc2398c8430af1c09e7343f6": 0.1
},

"paymentProcessing": {
    "enabled": true,
    "paymentInterval": 30,
    "minimumPayment": 0.01,
    "daemon": {
        "host": "127.0.0.1",
        "port": 9998,
        "user": "username",
        "password": "password"
    }
},

"ports": {
    "3008": {
        "diff": 8
    },
    "3032": {
        "diff": 32,
        "varDiff": {
            "minDiff": 8,
            "maxDiff": 512,
            "targetTime": 15,
            "retargetTime": 90,
            "variancePercent": 30
        }
    },
    "3256": {
        "diff": 256
    }
},

"daemons": [
    {
        "host": "127.0.0.1",
        "port": 9998,
        "user": "username",
        "password": "password"
    }
],

"p2p": {
    "enabled": false,
    "host": "127.0.0.1",
    "port": 9999,
    "disableTransactions": false
},

"mposMode": {
    "enabled": false,
    "host": "127.0.0.1",
    "port": 3306,
    "user": "me",
    "password": "mypass",
    "database": "ltc",
    "checkPassword": false,
    "autoCreateWorker": false
}

}

or could be something else? Thanks guys! I really appreciate the help. You guys are awesome!

**Comment by oelke** [comment]
For Dashcoin mining you will need some badass hashrate to find a block (10+Gh), difficulty is VERY high already on the network. Do you see shares being accepted with this setup?

**Comment by hiroshi2701** [comment]
Got that oelke. Yes. so far the mining pool has **1303** valid shares but no pending/confirmed/orphaned
![2016-09-27_1310](https://cloud.githubusercontent.com/assets/22319918/18860983/851b3ad6-84b4-11e6-8127-3dd31733bff8.png)

so if miners don't get blocks, there will be no coins will be paid for that miners. Is that correct? 
**BLOCK = COINS**

**Comment by hiroshi2701** [comment]
now I redirected all my miners to the pool
![2016-09-27_1353](https://cloud.githubusercontent.com/assets/22319918/18861698/d7460dfe-84b9-11e6-98dd-3d8d8a243d4f.png)

**Comment by oelke** [comment]
With that hashrate, try diff 16384, with dash I personally would not use anything less than 1024.
And yes, you only get $$ finding a block and it don't get orphaned.

On the pool config file, the line: 
"address": "[dash wallet address where]",
is where you put the address of the wallet that will receive the Reward when a block is found.

These Lines:
"rewardRecipients": {
"n37vuNFkXfk15uFnGoVyHZ6PYQxppD3QqK": 1.5,
"22851477d63a085dbc2398c8430af1c09e7343f6": 0.1
},
Are used to collect fees and such.

**Comment by hiroshi2701** [comment]
On the dash.json, 
should I change 
_"3256": {
"diff": 256
}
},_

to 

_"3256": {
"diff": 16384
}
},_

for example, I owned the mining pool, can I just remove the addresses on "rewardRecipients", oelke? 

Thank you so much! 
Mark

**Comment by oelke** [comment]
I really don't know what would happen if you remove it totally.But try this:
"rewardRecipients": {
"Same Address of the field "address" ": 1
},

This way the fee goes into the same wallet, and you avoid breaking things up.

And according the first post, the payment processor isn't working there:
[2016-09-20 11:27:57.677] [ERROR] [default] - Payments dash Error with payment processing daemon {"type":"offline","message":"connect ECONNREFUSED"}

on NOMP this is regarded REDIS not being available. That is ok If you don't want anyone else mining at your pool, but if someone does, they will never get paid.

**Comment by hiroshi2701** [comment]
Thanks so much! Got that Oelke.  

But I want tell you this first. On the "Address", what I put here before is the address I got when I first set up the **DASHCOIN WALLET** using _./dashcoin-cli getnewaddress_ when I first setup my **unomp mining pool.** 

on the other hand, Is this fine Oelke? 
**dash.json:**
![2016-09-27_2214](https://cloud.githubusercontent.com/assets/22319918/18877424/cf2266f4-84ff-11e6-82bf-d183f03f04ec.png)

You the man!

**Comment by oelke** [comment]
Yeap that is fine and way more suitable to you mining speed.
Don't forget to check on some of the miners if they actually at that diff.

**Comment by oelke** [comment]
Gave UP?

**Comment by hiroshi2701** [comment]
Never Oelke! :) I'm having a problem with my miners. When I redirected and switched my miners to port "3256", diff "16384, it went 0Khz. 

How do I check if the miners are at that diff, Oelke? Thanks for your help. You the man Oelke!!!

**Comment by oelke** [comment]
I dunno which miner do you got, but on the status screen on them, that will be displayd

**Comment by hiroshi2701** [comment]
okay Oelke. So the higher the hash rate, the higher the diff? Is that correct? 

for hash rate 600mz (1 miner), what would be the appropriate diff?   

All is running perfectly fine on the stratum server. The only thing I noticed is the "no new block"
![2016-09-30_1305](https://cloud.githubusercontent.com/assets/22319918/18981198/8d5c5c6e-870e-11e6-9417-f7bc7ec8f050.png)

and the POSIX not installed
![2016-09-30_1306](https://cloud.githubusercontent.com/assets/22319918/18981225/c4629ff2-870e-11e6-899d-d677a14e8bd3.png)

I really appreciate your help Oelke. Your the man!

**Comment by oelke** [comment]
Try enabling P2P:
Add into: unomp/coins/dash.json:
{
"name": "Dash",
"symbol": "DASH",
"algorithm": "x11",
"mposDiffMultiplier": 256**,**
**"peerMagic": "bf0c6bbd"**
}

And enable it on the pool config file:

"p2p": {
"enabled": **true**,
"host": "127.0.0.1",
"port": 9999,
"disableTransactions": **true**
},

for some reason it's (may) not being detected through RPC.

And yes again, bigger the hashrate bigger the diff, for 600mh/s try 8192.

**Comment by oelke** [comment]
still trying?

**Comment by wuhuaping** [comment]
/nomp# node init.js
/var/www/html/nomp/node_modules/stratum-pool/node_modules/multi-hashing/node_modules/bindings/bindings.js:83
        throw e
        ^

Error: Module did not self-register.
    at Error (native)
    at Object.Module._extensions..node (module.js:568:18)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at bindings (/var/www/html/nomp/node_modules/stratum-pool/node_modules/multi-hashing/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/var/www/html/nomp/node_modules/stratum-pool/node_modules/multi-hashing/index.js:1:99)
    at Module._compile (module.js:541:32)
Who can tell me how to solve it, thank you angel77758@163.com

**Comment by oelke** [comment]
Did **npm update** finished without error?

**Comment by wuhuaping** [comment]
"peerMagic": "bf0c6bbd"  Where can I find it

**Comment by wuhuaping** [comment]
达世币钱包的

**Comment by oelke** [comment]
You need to insert it into file:
coins/darkcoin.json (or wherever filename you are using, I'm using dash.json):
**{
    "name": "DASH",
    "symbol": "DASH",
    "algorithm": "x11",
    "mposDiffMultiplier": 256,
    "peerMagic": "bf0c6bbd"
}**

**Comment by wuhuaping** [comment]
Thank you for your answer.
I started it but dug dash did not dig a block
The address is correct.
Is not the problem of algorithm ah
I've been digging all night.
1G

**Comment by wuhuaping** [comment]
Start without any erro

**Comment by oelke** [comment]
mining with how much hashrate?

**Comment by oelke** [comment]
big 0 there, try lowering the difficulty on pool config file.

**Comment by wuhuaping** [comment]
"ports": {
        "5555": {
            "diff": 0.08
        },
        "6666": {
            "diff": 0.08,
            "varDiff": {
                "minDiff": 0.01,
                "maxDiff": 0.1,
                "targetTime": 15,
                "retargetTime": 90,
                "variancePercent": 30
            }
        },
        "8888": {
            "diff": 0.08
I set this but is not even if I can not find the block is heightening useless
I don't know where I was wrong.
Thank you for answering

At 2017-01-06 05:58:52, "oelke" <notifications@github.com> wrote:


big 0 there, try lowering the difficulty on pool config file.

**Comment by oelke** [comment]
that diff for DASH is kinda low, but it should appear at the hashrate field. what miner are u using?
