### ISSUE TITLE
nomp Error: Callback was already called

### ISSUE THREAD

**Issue by cristiycv** [zone117x/node-open-mining-portal#470]
Hello,

     I'm not sure if this is a bug or not, i have installed from manual.

`root@Front-pool01:/home/ubuntu/nomp# node init.js
2016-11-08 10:43:20 [POSIX]     [Connection Limit] (Safe to ignore) POSIX module not installed and resource (connection) limit was not raised
2016-11-08 10:43:20 [Master]    [CLI] CLI listening on port 17117
2016-11-08 10:43:20 [Master]    [PoolSpawner] Spawned 1 pool(s) on 2 thread(s)
2016-11-08 10:43:21 [Profit]    [Config] No alternative coins to switch to in current config, switching disabled.
2016-11-08 10:43:21 [Payments]  [litecoin] Error detecting number of satoshis in a coin, cannot do payment processing. Tried parsing: {"result":0.00000000,"error":null,"id":1478630601367}

/home/ubuntu/nomp/node_modules/async/dist/async.js:985
        if (fn === null) throw new Error("Callback was already called.");
                               ^
Error: Callback was already called.
    at /home/ubuntu/nomp/node_modules/async/dist/async.js:985:32
    at /home/ubuntu/nomp/node_modules/async/dist/async.js:3850:13
    at apply (/home/ubuntu/nomp/node_modules/async/dist/async.js:41:25)
    at /home/ubuntu/nomp/node_modules/async/dist/async.js:76:12
    at /home/ubuntu/nomp/libs/paymentProcessor.js:98:21
    at itemFinished (/home/ubuntu/nomp/node_modules/stratum-pool/lib/daemon.js:156:36)
    at /home/ubuntu/nomp/node_modules/stratum-pool/lib/daemon.js:169:17
    at parseJson (/home/ubuntu/nomp/node_modules/stratum-pool/lib/daemon.js:85:17)
    at IncomingMessage.<anonymous> (/home/ubuntu/nomp/node_modules/stratum-pool/lib/daemon.js:95:17)
    at IncomingMessage.emit (events.js:117:20)
2016-11-08 10:43:21 [Master]    [Payment Processor] Payment processor died, spawning replacement...
2016-11-08 10:43:21 [Website]   [Server] Website started on 0.0.0.0:80
2016-11-08 10:43:21 [Switching] [Setup] (Thread 1) Loading last proxy state from redis
2016-11-08 10:43:21 [Pool]      [litecoin] (Thread 1) Share processing setup with redis (127.0.0.1:6379)
2016-11-08 10:43:21 [Pool]      [litecoin] (Thread 1) Stratum Pool Server Started for litecoin [LTC] {scrypt}
                                                Network Connected:      Mainnet
                                                Detected Reward Type:   POW
                                                Current Block Height:   1093980
                                                Current Connect Peers:  8
                                                Current Block Diff:     3665937506.425635
                                                Network Difficulty:     3665937506.425897
                                                Network Hash Rate:      1.37 TH
                                                Stratum Port(s):        3032, 3256
                                                Pool Fee Percent:       0.5%
                                                Block polling every:    1000 ms
2016-11-08 10:43:21 [Switching] [Setup] (scrypt) Setting proxy difficulties after pool start
2016-11-08 10:43:21 [Switching] [Setup] (Thread 2) Loading last proxy state from redis
2016-11-08 10:43:21 [Pool]      [litecoin] (Thread 2) Share processing setup with redis (127.0.0.1:6379)
2016-11-08 10:43:21 [Pool]      [litecoin] (Thread 2) Stratum Pool Server Started for litecoin [LTC] {scrypt}
2016-11-08 10:43:21 [Switching] [Setup] (scrypt) Setting proxy difficulties after pool start

/home/ubuntu/nomp/libs/paymentProcessor.js:28
        coins.forEach(function(coin){
              ^
TypeError: Object true has no method 'forEach'
    at /home/ubuntu/nomp/libs/paymentProcessor.js:28:15
    at /home/ubuntu/nomp/node_modules/async/dist/async.js:484:16
    at /home/ubuntu/nomp/node_modules/async/dist/async.js:3477:13
    at /home/ubuntu/nomp/node_modules/async/dist/async.js:484:16
    at iteratorCallback (/home/ubuntu/nomp/node_modules/async/dist/async.js:1082:13)
    at /home/ubuntu/nomp/node_modules/async/dist/async.js:988:16
    at /home/ubuntu/nomp/node_modules/async/dist/async.js:3467:17
    at /home/ubuntu/nomp/libs/paymentProcessor.js:25:13
    at /home/ubuntu/nomp/libs/paymentProcessor.js:116:9
    at /home/ubuntu/nomp/node_modules/async/dist/async.js:3853:9
2016-11-08 10:43:23 [Master]    [Payment Processor] Payment processor died, spawning replacement...
2016-11-08 10:43:26 [Payments]  [litecoin] Error detecting number of satoshis in a coin, cannot do payment processing. Tried parsing: {"result":0.00000000,"error":null,"id":1478630606417}

/home/ubuntu/nomp/node_modules/async/dist/async.js:985
        if (fn === null) throw new Error("Callback was already called.");
                               ^
Error: Callback was already called.
    at /home/ubuntu/nomp/node_modules/async/dist/async.js:985:32
    at /home/ubuntu/nomp/node_modules/async/dist/async.js:3850:13
    at apply (/home/ubuntu/nomp/node_modules/async/dist/async.js:41:25)
    at /home/ubuntu/nomp/node_modules/async/dist/async.js:76:12
    at /home/ubuntu/nomp/libs/paymentProcessor.js:98:21
    at itemFinished (/home/ubuntu/nomp/node_modules/stratum-pool/lib/daemon.js:156:36)
    at /home/ubuntu/nomp/node_modules/stratum-pool/lib/daemon.js:169:17
    at parseJson (/home/ubuntu/nomp/node_modules/stratum-pool/lib/daemon.js:85:17)
    at IncomingMessage.<anonymous> (/home/ubuntu/nomp/node_modules/stratum-pool/lib/daemon.js:95:17)
    at IncomingMessage.emit (events.js:117:20)
2016-11-08 10:43:26 [Master]    [Payment Processor] Payment processor died, spawning replacement...
2016-11-08 10:43:28 [Payments]  [litecoin] Error detecting number of satoshis in a coin, cannot do payment processing. Tried parsing: {"result":0.00000000,"error":null,"id":1478630608938}

/home/ubuntu/nomp/node_modules/async/dist/async.js:985
        if (fn === null) throw new Error("Callback was already called.");
                               ^
Error: Callback was already called.
    at /home/ubuntu/nomp/node_modules/async/dist/async.js:985:32
    at /home/ubuntu/nomp/node_modules/async/dist/async.js:3850:13
    at apply (/home/ubuntu/nomp/node_modules/async/dist/async.js:41:25)
    at /home/ubuntu/nomp/node_modules/async/dist/async.js:76:12
    at /home/ubuntu/nomp/libs/paymentProcessor.js:98:21
    at itemFinished (/home/ubuntu/nomp/node_modules/stratum-pool/lib/daemon.js:156:36)
    at /home/ubuntu/nomp/node_modules/stratum-pool/lib/daemon.js:169:17
    at parseJson (/home/ubuntu/nomp/node_modules/stratum-pool/lib/daemon.js:85:17)
    at IncomingMessage.<anonymous> (/home/ubuntu/nomp/node_modules/stratum-pool/lib/daemon.js:95:17)
    at IncomingMessage.emit (events.js:117:20)
2016-11-08 10:43:28 [Master]    [Payment Processor] Payment processor died, spawning replacement...

`

**Comment by innova-market** [comment]
This error I have

**Comment by oelke** [comment]
Check node version, must be 0.10.xx
Change these lines in the end of package.json:

"mysql": "*",
"async": "1.5.2",
"express": "*",
"body-parser": "*",
"compression": "*",
"dot": "*",
"colors": "*",
"node-watch": "*",
"request": "*",
"nonce": "1.0.3",
"bignum": "0.11.0",
"extend": "3.0.0"

That should do the trick, DON'T forget to donate to Matthew: BTC: 1KRotMnQpxu3sePQnsVLRy3EraRFYfJQFR
