### ISSUE TITLE
Dear Hello, I'm running. Cannot find module'bignum'Error:

### ISSUE THREAD

**Issue by wuhuaping** [zone117x/node-open-mining-portal#472]
Dear Hello, I have a question to run. Can you tell me how to solve it, I look up a lot of information to solve this problem.
mail:   angel77758@163.com
root@Huaping:~/nomp# node init.js
Module.js:442
Err throw;
^
Cannot find module'bignum'Error:
at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/node_modules/stratum-pool/lib/algoProperties.js:1:76)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)

**Comment by wuhuaping** [comment]
root@Huaping:~/nomp# node init.js
/root/nomp/node_modules/stratum-pool/node_modules/multi-hashing/node_modules/bindings/bindings.js:83
throw e
^

Error: Module did not self-register.
at Error (native)
谁能告诉我怎么办呀 有没有人呀  亲爱的作者 怎么办呀  怎么解决这个问题呀  还有广大的爱好者们   你们是怎么解决的呀
