### ISSUE TITLE
Node init.js persistent error

### ISSUE THREAD

**Issue by blackice2013** [zone117x/node-open-mining-portal#475]
I'm getting this error when I do node init.js:

SyntaxError: Unexpected token (
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/pool/nomp/node_modules/stratum-pool/lib/index.js:5:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

Using node 0.10.46
npm update did success, just warning messages, but no errors.
Tryed several times with clear ubuntu 16.04 
Any can help?
Ty!

**Comment by oelke** [comment]
I think some change has been made to the stratum-pool module, crashing now. Tried to install here and got the same error.

**Comment by blackice2013** [comment]
Yea.. I cannot make it work anymore..
tried several node versions and clean installations and no way.
Any can help?

**Comment by AndreyNag** [comment]
Have the same errore.
~/nomp$ node -v
v0.10.48
~/nomp$ npm -v
2.15.1
~/nomp$ uname -a
Linux rostov 4.4.0-87-generic #110~14.04.1-Ubuntu SMP Tue Jul 18 14:52:28 UTC 2017 i686 athlon i686 GNU/Linux

```
~/nomp$ sudo node init.js

/home/root2pool/nomp/node_modules/bignum/node_modules/node-pre-gyp/node_modules/npmlog/node_modules/are-we-there-yet/node_modules/delegates/index.js:92
});
 ^
SyntaxError: Unexpected token )
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/root2pool/nomp/node_modules/bignum/node_modules/node-pre-gyp/node_modules/npmlog/node_modules/are-we-there-yet/tracker-stream.js:4:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

```
