### ISSUE TITLE
node init.js

### ISSUE THREAD

**Issue by aspirecoin** [zone117x/node-open-mining-portal#476]
root@aspire:~/nomp# node init.js

/root/nomp/node_modules/stratum-pool/lib/util.js:79
        var buff <= new Buffer(3);
                 ^^
SyntaxError: Unexpected token <=
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/nomp/node_modules/stratum-pool/lib/algoProperties.js:3:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
root@aspire:~/nomp# mc

**Comment by aspirecoin** [comment]
algo x11

**Comment by zone117x** [comment]
Should be fixed now with this https://github.com/zone117x/node-stratum-pool/commit/1b8c7086be986cb80dde76b83f45c37cdecc23cc
