### ISSUE TITLE
[ERROR]  Failed at the multi-hashing@0.0.9 install script.

### ISSUE THREAD

**Issue by sflyer** [zone117x/node-open-mining-portal#493]
Hi! Maybe somebody can help me with problem.
I'm try to install on Ubuntu server 16.04 - node-cryptonote-pool.
Installed packetges(all worked):
1)monero deamon 
2) Node.js v0.10
3)Redis-server 
4) libssl-dev libboost-all-dev
I'm running command "npm update" and have error.
Error's  in the log file:
```
4623 silly install multi-hashing@0.0.9
4624 info lifecycle multi-hashing@0.0.9~install: multi-hashing@0.0.9
4625 verbose lifecycle multi-hashing@0.0.9~install: unsafe-perm in lifecycle false
4626 verbose lifecycle multi-hashing@0.0.9~install: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home/user/node-cryptonote-pool/node_modules/multi-hashing/node_modules/.bin:/home/user/n$
4627 verbose lifecycle multi-hashing@0.0.9~install: CWD: /home/user/node-cryptonote-pool/node_modules/multi-hashing
4628 silly lifecycle multi-hashing@0.0.9~install: Args: [ '-c', 'node-gyp rebuild' ]
4629 silly lifecycle multi-hashing@0.0.9~install: Returned: code: 1  signal: null
4630 info lifecycle multi-hashing@0.0.9~install: Failed to exec install script
4631 verbose unlock done using /home/user/.npm/_locks/staging-0581618819f57e92.lock for /home/user/node-cryptonote-pool/node_modules/.staging
4632 verbose stack Error: multi-hashing@0.0.9 install: `node-gyp rebuild`
4632 verbose stack Exit status 1
4632 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:283:16)
4632 verbose stack     at emitTwo (events.js:87:13)
4632 verbose stack     at EventEmitter.emit (events.js:172:7)
4632 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
4632 verbose stack     at emitTwo (events.js:87:13)
4632 verbose stack     at ChildProcess.emit (events.js:172:7)
4632 verbose stack     at maybeClose (internal/child_process.js:821:16)
4632 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
4633 verbose pkgid multi-hashing@0.0.9
4634 verbose cwd /home/user/node-cryptonote-pool
4635 verbose Linux 4.4.0-83-generic
4636 verbose argv "/usr/bin/nodejs" "/usr/local/bin/npm" "update"
4637 verbose node v4.2.6
4638 verbose npm  v5.0.4
4639 error code ELIFECYCLE
4640 error errno 1
4641 error multi-hashing@0.0.9 install: `node-gyp rebuild`
4641 error Exit status 1
4642 error Failed at the multi-hashing@0.0.9 install script.

```
Any idea about error?

**Comment by sflyer** [comment]
For fix i'm changed ubuntu 16.04 to ubuntu 14.04 and all works fine!

**Comment by tw4w3t** [comment]
You can use 'apt install nodejs=0.10*' and then 'npm update'.
It helped me solve the problem. :+1:
