### ISSUE TITLE
Nomp Continued Development

### ISSUE THREAD

**Issue by krisklosterman** [zone117x/node-open-mining-portal#494]
If you would like to continue development on NOMP

Please join
https://join.slack.com/nomp/shared_invite/MjA5Nzk0MzE2NDcwLTE0OTkzNjY3NTMtMTc5ODY1OTQ5OA

Need to work on getting NOMP updated to latest version of Node and NPM, and also finish up the web portion of the site. I would like to extend it to allow logins and creation of workers potentially. Also want to use material and angularJS for front end

**Comment by zone117x** [comment]
👍

**Comment by 88plug** [comment]
Here to help!

**Comment by DanielCambray** [comment]
Hi,

I may have some time to look further on NOMP. Tell me how you see things and how we could work together.

**Comment by krisklosterman** [comment]
I have forks listed in the slack channel provided above, my plan is to get them throughly tested and hopefully pulled into this main.

I've updated code is updated to use the latest version of node. I've tested 8.1.x, 8.2.x, 8.3.x and so far it seems to work.
https://github.com/krisklosterman/node-open-mining-portal
https://github.com/krisklosterman/node-stratum-pool
https://github.com/krisklosterman/node-multi-hashing

@zone117x @DanielCambray

**Comment by DanielCambray** [comment]
Ok, I will try your repo on various coins.

**Comment by foxer666** [comment]
@krisklosterman, good day!
Is it tested with Scrypt-Jane?

**Comment by zone117x** [comment]
@krisklosterman Great work. I'm keeping an eye out for a good pull request. If it's a quality pull request then I'd love to make you a maintainer of this project.

**Comment by krisklosterman** [comment]
@foxer666 I need to re-enable scrypt-Jane and fix the errors I was getting. I will let you know when that is working

**Comment by foxer666** [comment]
@krisklosterman, many thanks to You.
Old version of NOMP don't  works with Jane. All looks fine, but new blocks not confirm with stratum.

**Comment by krisklosterman** [comment]
@foxer666 Ok I updated the code to add scrypt jane back in. Please test. Keep in mind I did not change anything but updating the code to support the new node version. Please pull and test a scrypt jane coin and let me know what you find. If you get errors, send them to me here or in the slack channel. Also let me know what coin you were testing with. Thanks!

**Comment by foxer666** [comment]
@krisklosterman 
```
git clone https://github.com/krisklosterman/node-open-mining-portal.git nompnew
nvm install v8.4.0
nvm use v8.4.0
npm update
```
`npm WARN optional SKIPPING OPTIONAL DEPENDENCY: co@4.6.0 (node_modules/co):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: request to https://registry.npmjs.org/co/-/co-4.6.0.tgz failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org:443

npm ERR! code EAI_AGAIN
npm ERR! errno EAI_AGAIN
npm ERR! request to https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.8.tgz failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org:443

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-08-16T18_43_36_039Z-debug.log
`

**Comment by krisklosterman** [comment]
@foxer666 
We can move this over to that fork if you want, no reason to dirty up this thread :)
Something is up with your NPM

Try with sudo if needed
npm install -g n
n 8.3.0
npm update -g npm

git clone https://github.com/krisklosterman/node-open-mining-portal.git nompnew
cd nompnew
npm update

node init.js after configs are setup

**Comment by foxer666** [comment]
@krisklosterman 
Pleae open issue or give me a link for move this to that fork. I can not open issue there.

**Comment by foxer666** [comment]
@krisklosterman 
```
root@mining:~# npm install -g n
npm http GET https://registry.npmjs.org/n
npm http 200 https://registry.npmjs.org/n
npm http GET https://registry.npmjs.org/n/-/n-2.1.8.tgz
npm http 200 https://registry.npmjs.org/n/-/n-2.1.8.tgz
/root/.nvm/v0.10.25/bin/n -> /root/.nvm/v0.10.25/lib/node_modules/n/bin/n
n@2.1.8 /root/.nvm/v0.10.25/lib/node_modules/n
root@mining:~# n 8.3.0

     install : node-v8.3.0
       mkdir : /usr/local/n/versions/node/8.3.0
       fetch : https://nodejs.org/dist/v8.3.0/node-v8.3.0-linux-x64.tar.gz
######################################################################## 100,0%
   installed : v0.10.25

root@mining:~# npm update -g npm
npm http GET https://registry.npmjs.org/npm/latest
npm http 200 https://registry.npmjs.org/npm/latest
npm http GET https://registry.npmjs.org/npm
npm http 200 https://registry.npmjs.org/npm
npm http GET https://registry.npmjs.org/npm/-/npm-5.3.0.tgz
npm http 200 https://registry.npmjs.org/npm/-/npm-5.3.0.tgz
npm http GET https://registry.npmjs.org/npm/5.3.0
npm http 200 https://registry.npmjs.org/npm/5.3.0
npm http GET https://registry.npmjs.org/npm/-/npm-5.3.0.tgz
npm http 200 https://registry.npmjs.org/npm/-/npm-5.3.0.tgz
npm WARN package.json path-is-inside@1.0.2 No README data
npm WARN package.json sorted-object@2.0.1 No README data
/root/.nvm/v0.10.25/bin/npx -> /root/.nvm/v0.10.25/lib/node_modules/npm/bin/npx-cli.js
/root/.nvm/v0.10.25/bin/npm -> /root/.nvm/v0.10.25/lib/node_modules/npm/bin/npm-cli.js
npm@5.3.0 /root/.nvm/v0.10.25/lib/node_modules/npm
root@mining:~# git clone https://github.com/krisklosterman/node-open-mining-portal.git nompnew
Клонирование в «nompnew»…
remote: Counting objects: 2593, done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 2593 (delta 4), reused 10 (delta 4), pack-reused 2581
Получение объектов: 100% (2593/2593), 737.20 KiB | 490.00 KiB/s, готово.
Определение изменений: 100% (1565/1565), готово.
root@mining:~# cd nompnew
root@mining:~/nompnew# npm update

/root/.nvm/v0.10.25/lib/node_modules/npm/lib/config/cmd-list.js:113
module.exports.aliases = Object.assign({}, shorthands, affordances)
                                ^
TypeError: Object function Object() { [native code] } has no method 'assign'
    at Object.<anonymous> (/root/.nvm/v0.10.25/lib/node_modules/npm/lib/config/cmd-list.js:113:33)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /root/.nvm/v0.10.25/lib/node_modules/npm/lib/npm.js:37:17
    at Object.<anonymous> (/root/.nvm/v0.10.25/lib/node_modules/npm/lib/npm.js:471:3)
    at Module._compile (module.js:456:26)
root@mining:~/nompnew#
```

**Comment by krisklosterman** [comment]
Ok taking a look, I am able to duplicate error, I opened up issues on the forks @foxer666

**Comment by gewure** [comment]
Subscribed!

**Comment by foxer666** [comment]
@gewure 
https://github.com/krisklosterman/node-open-mining-portal/issues/2

**Comment by sabbotkicker** [comment]
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.0-116-generic
gyp ERR! command "/usr/local/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/jatinmetlaw5/nompnew/node_modules/multi-hashing
gyp ERR! node -v v8.3.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! multi-hashing@0.0.9 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the multi-hashing@0.0.9 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
