### ISSUE TITLE
TypeError: Cannot call method 'apply' of undefined

### ISSUE THREAD

**Issue by jcreyesb** [zone117x/node-open-mining-portal#511]
i created algo in algoproperties.js, the pool work ok, but when the worker start mining.. i have this

/home/ubuntu/unomp/node_modules/merged-pooler/lib/algoProperties.js:227
                return multiHashing.m7mhash.apply(this, arguments);
                                            ^
TypeError: Cannot call method 'apply' of undefined
    at /home/ubuntu/unomp/node_modules/merged-pooler/lib/algoProperties.js:227:45
    at JobManager.processShare (/home/ubuntu/unomp/node_modules/merged-pooler/lib/jobManager.js:263:26)
    at null.<anonymous> (/home/ubuntu/unomp/node_modules/merged-pooler/lib/pool.js:630:46)
    at EventEmitter.emit (events.js:117:20)
    at handleSubmit (/home/ubuntu/unomp/node_modules/merged-pooler/lib/stratum.js:175:15)
    at handleMessage (/home/ubuntu/unomp/node_modules/merged-pooler/lib/stratum.js:88:17)
    at /home/ubuntu/unomp/node_modules/merged-pooler/lib/stratum.js:248:25
    at Array.forEach (native)
    at Socket.<anonymous> (/home/ubuntu/unomp/node_modules/merged-pooler/lib/stratum.js:234:26)
    at Socket.EventEmitter.emit (events.js:95:17)

**Comment by foxer666** [comment]
https://github.com/UNOMP/unified-node-open-mining-portal/issues/213
