### ISSUE TITLE
const Hoek = require('hoek');

### ISSUE THREAD

**Issue by jcreyesb** [zone117x/node-open-mining-portal#512]
/home/pool/nomp/node_modules/request/node_modules/hawk/node_modules/boom/lib/index.js:5
const Hoek = require('hoek');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/pool/nomp/node_modules/request/node_modules/hawk/lib/index.js:5:33)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
------------------------------------------------------------------------------------------------------

i installed hoek, 
pool@ubuntu143:~/nomp$ sudo npm install hoek
npm http GET https://registry.npmjs.org/hoek
npm http 304 https://registry.npmjs.org/hoek
npm WARN engine hoek@5.0.0: wanted: {"node":">=8.0.0"} (current: {"node":"v0.10.25","npm":"1.3.10"})
hoek@5.0.0 node_modules/hoek

but when i run node init.js i have the same message

**Comment by jcreyesb** [comment]
I searched in Google, the answers was, update node, but, when i update node the systematic generate more errors

**Comment by jcreyesb** [comment]
Can NOMP work with node >=6?

**Comment by foxer666** [comment]
Yes
https://github.com/krisklosterman/node-open-mining-portal

**Comment by PunkSp** [comment]
Did you get it work?

**Comment by jcreyesb** [comment]
No, i didn't

**Comment by PunkSp** [comment]
Got it work... copied all node_modules from a unomp working instance, and added the stratum module..

**Comment by PunkSp** [comment]
Ive made a new instalation.. same issue.. but this time, Ive just changed one module:
/node_modules/request/node_modules/hawk
Took the same folder from unomp (after npm update) and it worked.... seems to be easy to fix, as on unomp is working.... someone knows?

**Comment by foxer666** [comment]
@PunkSp 
NOMP use last version of request module:
https://github.com/zone117x/node-open-mining-portal/blob/master/package.json
UNOMP use 2.69.0 version of request module:
https://github.com/UNOMP/unified-node-open-mining-portal/blob/master/package.json

Change it in package.json file and do npm update

**Comment by PunkSp** [comment]
Hummm nice @foxer666 !!!! Many Thanks!!!!!!

**Comment by Andrewblood** [comment]
I have the same problem but i have not the same folder from unomp...
any help?

**Comment by coinsinternet** [comment]
For me replacing package.json  doesnt work, because its kicking in a  BIGNUM  error

**Comment by PunkSp** [comment]
Dont try to replace de package.json.  What Ive done was editing the file and change the hawk version. UNOMP uses a specific version, and NOMP is set to use the last version.

**Comment by srpmatt** [comment]
I'm getting the same error, is there a fix for it?

**Comment by virtualjj** [comment]
@srpmatt what @foxer666 suggested worked for me. 

In your cloned NOMP folder you should see the following files:

```
stratumuser@ip-172-31-31-164:~/nomp$ ls -la
total 116
drwxrwxr-x  9 stratumuser stratumuser  4096 Jan 10 05:41 .
drwxr-xr-x  9 stratumuser stratumuser  4096 Jan 10 05:41 ..
drwxrwxr-x  2 stratumuser stratumuser  4096 Jan 10 04:49 coins
-rw-rw-r--  1 stratumuser stratumuser  2815 Jan 10 04:37 config_example.json
-rw-rw-r--  1 stratumuser stratumuser  2816 Jan 10 04:47 config.json
drwxrwxr-x  8 stratumuser stratumuser  4096 Jan 10 04:37 .git
-rw-rw-r--  1 stratumuser stratumuser    89 Jan 10 04:37 .gitignore
-rw-rw-r--  1 stratumuser stratumuser 13800 Jan 10 04:37 init.js
drwxrwxr-x  2 stratumuser stratumuser  4096 Jan 10 04:37 libs
-rw-rw-r--  1 stratumuser stratumuser 18026 Jan 10 04:37 LICENSE
drwxrwxr-x 19 stratumuser stratumuser  4096 Jan 10 05:41 node_modules
-rw-rw-r--  1 stratumuser stratumuser  1412 Jan 10 05:41 package.json
drwxrwxr-x  2 stratumuser stratumuser  4096 Jan 10 05:00 pool_configs
-rw-rw-r--  1 stratumuser stratumuser 26156 Jan 10 04:37 README.md
drwxrwxr-x  2 stratumuser stratumuser  4096 Jan 10 04:37 scripts
drwxrwxr-x  4 stratumuser stratumuser  4096 Jan 10 04:37 website
```
Modify the `package.json` file and change `"request": "*",` to `"request": "2.69.0",`

Run `npm update` and then make sure Redis is running using command: `ps aux | grep redis`

You should see something similar to below assuming that you have a pool configured:

![image](https://user-images.githubusercontent.com/10323889/34757851-3e95cfd8-f617-11e7-8399-c29d4d24bf3b.png)

**Comment by srpmatt** [comment]
Thank you that is working

**Comment by lagwag0n** [comment]
Man I wish I would have seen this fix earlier.
