### ISSUE TITLE
PoolSpawner can not be started. events.js:72         throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by digitalhuman** [zone117x/node-open-mining-portal#540]
node init.js
2018-01-10 11:44:15 [POSIX]     [Connection Limit] (Safe to ignore) POSIX module not installed and resource (connection) limit was not raised
2018-01-10 11:44:15 [Master]    [CLI] CLI listening on port 17118
2018-01-10 11:44:17 [Master]    [PoolSpawner] Spawned 1 pool(s) on 4 thread(s)
2018-01-10 11:44:17 [Switching] [Setup] (Thread 1) Loading last proxy state from redis
2018-01-10 11:44:17 [Pool]      [digibyte] (Thread 1) Share processing setup with redis (127.0.0.1:6379)
2018-01-10 11:44:17 [Switching] [Setup] (Thread 1) Last proxy state loaded from redis

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: bind EADDRINUSE
    at errnoException (net.js:901:11)
    at net.js:1081:30
    at Object.2:1 (cluster.js:592:5)
    at handleResponse (cluster.js:171:41)
    at respond (cluster.js:192:5)
    at handleMessage (cluster.js:202:5)
    at process.EventEmitter.emit (events.js:117:20)
    at handleMessage (child_process.js:318:10)
    at child_process.js:392:7
    at process.handleConversion.net.Native.got (child_process.js:91:7)
2018-01-10 11:44:17 [Master]    [PoolSpawner] Fork 0 died, spawning replacement worker...

**Comment by foxer666** [comment]
```
POSIX module not installed
```

**Comment by digitalhuman** [comment]
@foxer666 doesn't matter. POSIX is for email but thanks anyway. It seems there was a pool already running on a port that I had configured.
