### ISSUE TITLE
dont start node

### ISSUE THREAD

**Issue by surixtrader** [zone117x/node-open-mining-portal#542]
Error: Cannot find module 'async'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/poolbrasil/node-open-mining-portal/init.js:6:13)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)

**Comment by foxer666** [comment]
npm update ?
