### ISSUE TITLE
Added support for Lyra2Z and NodeJS > 8.x.x

### ISSUE THREAD

**Issue by foxer666** [zone117x/node-open-mining-portal#545]
Good day!

We add support of Lyra2Z algorithm to NOMP. Tested with ZCoin.
https://github.com/foxer666/node-open-mining-portal
Working on neoscrypt support.

Glad to see all for testings and help.

**Comment by sabbotkicker** [comment]
yp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:180:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Linux 4.4.0-116-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/jatinmetlaw5/pool/node_modules/multi-hashing
gyp ERR! node -v v9.8.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! multi-hashing@1.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the multi-hashing@1.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
