### ISSUE TITLE
module.js:557 error

### ISSUE THREAD

**Issue by paketeh** [zone117x/node-open-mining-portal#559]
Hi

I'm having this problem when trying to start the node:

root@l3mpool-eu3:/opt/nomp# node init.js
module.js:557
    throw err;
    ^
Error: Cannot find module '/opt/nomp/node_modules/bignum/binding/bignum.node'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/nomp/node_modules/bignum/index.js:4:11)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)

I've tried npm update and re-done but keeps failing, any hint?

Many thanks!

- paketeh

**Comment by foxer666** [comment]
npm update done?

**Comment by paketeh** [comment]
Yes, did it orginally and done it again after the error.

**Comment by foxer666** [comment]
npm install
npm update
without sudo in pool folder
If it didn't help - try with sudo.

Check folder /nomp/node_modules/bignum

**Comment by Crazytoo01** [comment]
I am having major problem tried allmost everything 

  using ubuntu 16.04 follow the instruktions to a T i think 

 getting the same results as you 
can any one with a working server write what they have done ????

**Comment by bobozm** [comment]
cd unomp
nvm install 0.10.25
source ~/.bashrc
nvm use 0.10.25
sudo npm update

**Comment by paketeh** [comment]
> npm install
npm update
without sudo in pool folder
If it didn't help - try with sudo.
>
> Check folder /nomp/node_modules/bignum

Done npm install and update, bignum folder exists and contains files:

/opt/nomp/node_modules/bignum# ls
bignum.cc  binding.gyp  index.js  package.json  README.markdown

Same problem when trying to start node.js

> cd unomp
nvm install 0.10.25
source ~/.bashrc
nvm use 0.10.25
sudo npm update
node init.js
if any errr codes npm update was not successful

Still didn't work, gives me the same error when starting node.js.

Thanks in advance for the help!

**Comment by paketeh** [comment]
Any idea guys? I installed a VM with Ubuntu 16.04, maybe shall I choose an older OS? Any recommendation on version? I really don't mind, as long as I can get this working :)

**Comment by bobozm** [comment]
What's the err

**Comment by bobozm** [comment]
Delete bingum folder 
Node -v ( make sure it's 0.10.25)
Npm update

**Comment by paketeh** [comment]
>Delete bingum folder
Node -v ( make sure it's 0.10.25)
Npm update

Done, now it prompts me an error when performing npm update:

./sha1.c:4:25: fatal error: openssl/sha.h: No such file or directory
compilation terminated.
multihashing.target.mk:136: recipe for target 'Release/obj.target/multihashing/sha1.o' failed
make: *** [Release/obj.target/multihashing/sha1.o] Error 1
make: Leaving directory '/opt/nomp/node_modules/stratum-pool/node_modules/multi-hashing/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/.nvm/v0.10.25/lib/node_modules/npm/node_modules/node-gyp/lib/build
.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 4.13.0-1008-gcp
gyp ERR! command "node" "/root/.nvm/v0.10.25/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/nomp/node_modules/stratum-pool/node_modules/multi-hashing
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm ERR! multi-hashing@0.0.9 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the multi-hashing@0.0.9 install script.
npm ERR! This is most likely a problem with the multi-hashing package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls multi-hashing
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.13.0-1008-gcp
npm ERR! command "/root/.nvm/v0.10.25/bin/node" "/root/.nvm/v0.10.25/bin/npm" "update"
npm ERR! cwd /opt/nomp
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.24
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /opt/nomp/npm-debug.log
npm ERR! not ok code 0

Current installed versions

>root@l3mpool-eu3:/opt/nomp# node -v
v0.10.25
root@l3mpool-eu3:/opt/nomp# npm -v
1.3.24

redis up
>root@l3mpool-eu3:/opt/nomp# redis-cli ping
PONG

Bitcoin up
>root@l3mpool-eu3:/opt/nomp# bitcoin-cli getblockcount
505684

:/

**Comment by bobozm** [comment]
what does command
node -v show

**Comment by bobozm** [comment]
sorry I see it in log
npm install --save 
npm update

**Comment by paketeh** [comment]
When doing npm-install --save

>compilation terminated.
multihashing.target.mk:136: recipe for target 'Release/obj.target/multihashing/sha1.o' failed
make: *** [Release/obj.target/multihashing/sha1.o] Error 1
make: Leaving directory '/opt/nomp/node_modules/stratum-pool/node_modules/multi-hashing/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/.nvm/v0.10.25/lib/node_modules/npm/node_modules/node-gyp/lib/build
.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 4.13.0-1008-gcp
gyp ERR! command "node" "/root/.nvm/v0.10.25/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/nomp/node_modules/stratum-pool/node_modules/multi-hashing
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm ERR! multi-hashing@0.0.9 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the multi-hashing@0.0.9 install script.
npm ERR! This is most likely a problem with the multi-hashing package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls multi-hashing
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.13.0-1008-gcp
npm ERR! command "/root/.nvm/v0.10.25/bin/node" "/root/.nvm/v0.10.25/bin/npm" "install" "--save"
npm ERR! cwd /opt/nomp
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.24
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /opt/nomp/npm-debug.log
npm ERR! not ok code 0

When doing npm update

>compilation terminated.
multihashing.target.mk:136: recipe for target 'Release/obj.target/multihashing/sha1.o' failed
make: *** [Release/obj.target/multihashing/sha1.o] Error 1
make: Leaving directory '/opt/nomp/node_modules/stratum-pool/node_modules/multi-hashing/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/.nvm/v0.10.25/lib/node_modules/npm/node_modules/node-gyp/lib/build
.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 4.13.0-1008-gcp
gyp ERR! command "node" "/root/.nvm/v0.10.25/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/nomp/node_modules/stratum-pool/node_modules/multi-hashing
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm ERR! multi-hashing@0.0.9 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the multi-hashing@0.0.9 install script.
npm ERR! This is most likely a problem with the multi-hashing package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls multi-hashing
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.13.0-1008-gcp
npm ERR! command "/root/.nvm/v0.10.25/bin/node" "/root/.nvm/v0.10.25/bin/npm" "update"
npm ERR! cwd /opt/nomp
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.24
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /opt/nomp/npm-debug.log
npm ERR! not ok code 0

Maybe rm -r nomp and reinstall? :S

**Comment by bobozm** [comment]
Sudo npm install
Sudo npm update

**Comment by paketeh** [comment]
>Sudo npm install
Sudo npm update

Same output. This was already suggested by Foxer previously in the thread.

Maybe I'd reinstall again, any suggested os for the VM?

Thx!

**Comment by foxer666** [comment]
problem with sha1
try our repo. it works with node 9 last.

**Comment by paketeh** [comment]
>problem with sha1
try our repo. it works with node 9 last.

Sorry to ask, but how can I change this so npm doesn't use sha1?

**Comment by foxer666** [comment]
@paketeh 
I didn't thinks that it was right to delete sha
binding.gyp and rebuild.

**Comment by digitalhemanth** [comment]
-> Download and install latest version of **node Js** , 
-> clear cache using ' **npm clear cache** ' else delete npm cache @ appdata 
-> then install fresh npm using ' **npm install -g npm** 
->finally verify cache ' **_npm cache verify_** '
-> then install any package are angular cli using ' # npm install ' command

**Comment by sabbotkicker** [comment]
tried everything
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.0-116-generic
gyp ERR! command "/usr/local/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/jatinmetlaw5/pool/node_modules/multi-hashing
gyp ERR! node -v v8.3.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! multi-hashing@1.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the multi-hashing@1.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by devnull-ed** [comment]
Too recent node

**Comment by sabbotkicker** [comment]
upgrading to ubuntu 16 solved this issue  thanks for help
