### ISSUE TITLE
node init.js running error

### ISSUE THREAD

**Issue by goodthebest** [zone117x/node-open-mining-portal#563]
I've installed the package successfully and properly configured json files as suggested. However I'm getting this error when I start: node init.js

---------------------------- error---------------------------------------
module.js:340
    throw err;
          ^
Error: Cannot find module 'async'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/nomp/init.js:6:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

Could anyone please look into it?

**Comment by AndreyNag** [comment]
Look at this 

> error: Cannot find module 'async'
You must install module 'async'.
