### ISSUE TITLE
SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by TrueUW** [zone117x/node-open-mining-portal#565]
Trying to set this up and when I do "sudo node init.js" this shows up:

/home/roastedadmin/pool/node-open-mining-portal/init.js:258
    let cliHost = '';
        ^^^^^^^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

What did I do wrong here?

**Comment by devnull-ed** [comment]
You are messed up with repos. The above code is ran from this repo https://github.com/foxer666/node-open-mining-portal which requires fresh node.js.
