### ISSUE TITLE
Error: Cannot find module 'async'

### ISSUE THREAD

**Issue by solutionall** [zone117x/node-open-mining-portal#574]
I have this when I try "node init.js"
What should I do now? Could you help me solve the problem
```
Error: Cannot find module 'async'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/delgerdev/nomp/init.js:6:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)

```

**Comment by devnull-ed** [comment]
npm install

**Comment by speedynik** [comment]
^^ thank you

**Comment by CarmeloCampos** [comment]
@devnull-ed  thank you
