### ISSUE TITLE
npm install failed

### ISSUE THREAD

**Issue by sabbotkicker** [zone117x/node-open-mining-portal#577]
make: Leaving directory `/home/sabbotkicker/pool/node_modules/stratum-pool/node_modules/multi-hashing/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 4.4.0-116-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/sabbotkicker/pool/node_modules/stratum-pool/node_modules/multi-hashing
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm http 304 https://registry.npmjs.org/json-stable-stringify
npm WARN engine co@4.6.0: wanted: {"iojs":">= 1.0.0","node":">= 0.12.0"} (current: {"node":"v0.10.25","npm":"1.3.24"})
npm http GET https://registry.npmjs.org/jsonify
npm http 304 https://registry.npmjs.org/jsonify

> bignum@0.12.5 install /home/sabbotkicker/pool/node_modules/stratum-pool/node_modules/bignum
> node-pre-gyp install --fallback-to-build

module.js:340
    throw err;

**Comment by goodthebest** [comment]
@sabbotkicker what coins you want to mine and what algos? Perhaps you can contact me and I'll find a good solution for you.

**Comment by bcmonster** [comment]
I have scewed up my npm some how...  Im sure it was when changing versions... any help

the error i get on everything is... SyntaxError: Unexpected strict mode reserved word

pretty sure this is what did it.  Any ideas?

npm -g install n
n 0.10.36
node -v

**Comment by bcmonster** [comment]
Never Mind... I got it

sudo n stable

**Comment by devnull-ed** [comment]
Node.JS v8.0 minimum is required

**Comment by sabbotkicker** [comment]
i am trying to mine zoin coins its based on lyra2
