### ISSUE TITLE
ERROR:bignum/index.js:99 'Unspecified operation for type ' +

### ISSUE THREAD

**Issue by qshuai** [zone117x/node-open-mining-portal#581]
```
/nomp/node_modules/stratum-pool/node_modules/bignum/index.js:99
      throw new TypeError('Unspecified operation for type ' +
            ^
2018-03-21 11:54:35 [Payments]	[bitcoin] Finished interval - time spent: 8118ms total, 3ms redis, 8114ms daemon RPC
TypeError: Unspecified operation for type undefined for add
    at BigNum.(anonymous function) [as add] (/nomp/node_modules/stratum-pool/node_modules/bignum/index.js:99:13)
    at Object.base58.decode (/nomp/node_modules/stratum-pool/node_modules/base58-native/base58.js:49:23)
    at Object.exports.addressToScript (/nomp/node_modules/stratum-pool/lib/util.js:266:26)
    at /nomp/node_modules/stratum-pool/lib/pool.js:421:37
    at /nomp/node_modules/stratum-pool/lib/pool.js:423:15
    at /nomp/node_modules/stratum-pool/lib/daemon.js:134:13
    at parseJson (/nomp/node_modules/stratum-pool/lib/daemon.js:85:17)
    at IncomingMessage.<anonymous> (/nomp/node_modules/stratum-pool/lib/daemon.js:95:17)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
2018-03-21 11:54:35 [Master]	[PoolSpawner] Fork 1 died, spawning replacement worker...
2018-03-21 11:54:38 [Switching]	[Setup] (Thread 2) Loading last proxy state from redis
2018-03-21 11:54:38 [Pool]	[bitcoin] (Thread 2) Share processing setup with redis (127.0.0.1:6379)
2018-03-21 11:54:38 [Switching]	[Setup] (Thread 2) Switching "switch1" listening for sha256 on port 3333 into bitcoin
```
when I run node init.js, I encounter this error. help!
I setting up this pool for bitcoin-abc, and I have transform the bitcoin-abc address from new to old.

**Comment by garceri** [comment]
Start your abc node with -usecashaddr=0.

**Comment by qshuai** [comment]
Oh, Thanks very much!

**Comment by knkrth** [comment]
I got this error while using the latest bitcoin version v0.19

**Comment by raderack3948** [comment]
I'm also having this error with Bitcoin Core version v0.21.0.0.

Is there any solution to this problem?

**Comment by archimede2021** [comment]
I get this error using /Satoshi:24.0.1/ , which as far as I know doesn have usecashaddr=0
