### ISSUE TITLE
configure error

### ISSUE THREAD

**Issue by jdamhost** [zone117x/node-open-mining-portal#582]
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at ChildProcess.emit (events.js:180:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Linux 3.10.0-693.21.1.el7.x86_64
gyp ERR! command "/root/.nvm/versions/node/v9.9.0/bin/node" "/usr/local/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/miningpoolsco/node-open-mining-portal/node_modules
gyp ERR! node -v v9.9.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 

I have tried npm install, rebuild, node gyp-rebuild but get this error and npm install fails on multihashing

**Comment by jdamhost** [comment]
at bindings (/home/miningpoolsco/node-open-mining-portal/node_modules/bindings/bindings.js:93:9)
    at Object.<anonymous> (/home/miningpoolsco/node-open-mining-portal/node_modules/multi-hashing/index.js:1:99)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous>

**Comment by jdamhost** [comment]
209 verbose stack Error: /home/miningpoolsco/node-open-mining-portal/node_modules/stratum-pool: Appears to be a git repo or submodule.
209 verbose stack     at /root/.nvm/versions/node/v9.9.0/lib/node_modules/npm/node_modules/npm-install-checks/index.js:137:15
209 verbose stack     at /root/.nvm/versions/node/v9.9.0/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:287:18
209 verbose stack     at FSReqWrap.oncomplete (fs.js:171:5)
210 verbose cwd /home/miningpoolsco/node-open-mining-portal
211 verbose Linux 3.10.0-693.21.1.el7.x86_64
212 verbose argv "/root/.nvm/versions/node/v9.9.0/bin/node" "/root/.nvm/versions/node/v9.9.0/bin/npm" "update"
213 verbose node v9.9.0
214 verbose npm  v5.8.0
215 error path /home/miningpoolsco/node-open-mining-portal/node_modules/stratum-pool
216 error code EISGIT
217 error git /home/miningpoolsco/node-open-mining-portal/node_modules/stratum-pool: Appears to be a git repo or submodule.
218 error git /home/miningpoolsco/node-open-mining-portal/node_modules/stratum-pool
219 error git Refusing to remove it. Update manually,
219 error git or move it out of the way first.

**Comment by jdamhost** [comment]
all resolved
