### ISSUE TITLE
Using to sha256 in multport conflicts

### ISSUE THREAD

**Issue by red0bear** [zone117x/node-open-mining-portal#627]
Im trying to put two sha256 in multiport selection but i got this error em pool doens't see another node trying always to connect in frist one. The error sometimes appear ..... i would like to know if this is experimental or need more adjusts to work fine in configuration. 

/nomp/libs/poolWorker.js:278
                            pools[currentPool].getStratumServer().handleNewClient(socket);
                                                                 ^

TypeError: Cannot read property 'handleNewClient' of undefined
    at Server.<anonymous> (nomp/libs/poolWorker.js:278:66)
    at emitOne (events.js:116:13)
    at Server.emit (events.js:211:7)
    at Object.onconnection (net.js:1565:8)
    at onconnection (internal/cluster/child.js:178:12)
    at Worker.onmessage (internal/cluster/child.js:44:7)
    at process.onInternalMessage (internal/cluster/utils.js:42:8)
    at emitTwo (events.js:131:20)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)

**Comment by nicebbs** [comment]
Have you solved the problem yet?

**Comment by red0bear** [comment]
@nicebbs , not yet.
