### ISSUE TITLE
bignum error

### ISSUE THREAD

**Issue by linuxhus** [zone117x/node-open-mining-portal#630]
xmr@xmr-test:~/nomp$ npm update
npm WARN deprecated hoek@2.16.3: The major version is no longer supported. Please update to 4.x or newer

> bignum@0.12.5 install /home/xmr/nomp/node_modules/bignum
> node-pre-gyp install --fallback-to-build

/usr/bin/env: »node“: Datei oder Verzeichnis nicht gefunden
npm ERR! Linux 4.15.0-33-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "update"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! bignum@0.12.5 install: `node-pre-gyp install --fallback-to-build`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the bignum@0.12.5 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bignum package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bignum
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bignum
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/xmr/nomp/npm-debug.log

**Comment by MerlinMagic2018** [comment]
module.js:681
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module did not self-register.
    at Object.Module._extensions..node (module.js:681:18)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/merlin/Desktop/tabarnak/nomp/node_modules/stratum-pool/node_modules/bignum/index.js:4:11)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)





did what you said.... i guess I have to take the version you took when you posted this......

other wise I don't know what to do.........

**Comment by MerlinMagic2018** [comment]
because the latest commit, bignum@0.12.........

broke this......... so if I want an older version of stratum-pool, it jsut won't register stratum-pool's bignum.........

**Comment by MerlinMagic2018** [comment]
so i tried :

wget  https://github.com/zone117x/node-open-mining-portal/tree/4b4e18e564ca16ef965d7bf3ba59f0c4fdb460c0

npm install

( error when starting pool...... sudo node init.js returns error from 2 post above )
 
then  i proceed to ( above suggestion ) :

curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
and after:
nvm install 0.10.48
nvm use 0.10.48
nvm alias default 0.10.48
nvm use default

npm update



then I retry....... sudo node init.js.........

same error ............
module.js:681
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module did not self-register.
    at Object.Module._extensions..node (module.js:681:18)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/merlin/Desktop/calisse/nomp/node_modules/bignum/index.js:4:11)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)

what can I do ?

**Comment by MerlinMagic2018** [comment]
after last error, I tried 

nvm use 0.10.25
npm update

still dosent work.......... so I guess I can't make it work with the version of my coin

**Comment by dogui1718** [comment]
Hi! I have the same problem here! _(Ubuntu 20.04 LTS - Node v14.15.0)_ 
Are there any suggestions or is this project totally abandoned?

**Comment by zone117x** [comment]
@dogui1718 Feel free to make a PR for that fix, thank you!
