### ISSUE TITLE
Error..):

### ISSUE THREAD

**Issue by llt1256** [zone117x/node-open-mining-portal#631]
Error HELP ):

```
2018-09-11 13:10:17 [POSIX]     [Connection Limit] (Safe to ignore) POSIX module not installed and resource (connection) limit was not raised
2018-09-11 13:10:17 [Master]    [PoolSpawner] No pool configs exists or are enabled in pool_configs folder. No pools spawned.
2018-09-11 13:10:17 [Master]    [CLI] CLI listening on port 17117

2018-09-11 13:10:18 [Stats]     [Historics] Error when trying to grab historical stats {}
2018-09-11 13:10:18 [Stats]     [Historics] Error adding stats to historics [{},{},{},{}]
2018-09-11 13:10:18 [Stats]     [Historics] Redis for stats had an error {}
2018-09-11 13:10:18 [Website]   [Init] Failed grabbing coin version bytes from redis {}
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
    at RedisClient.on_error (/home/wecomoa/nomp/node_modules/redis/index.js:196:24)
    at Socket.<anonymous> (/home/wecomoa/nomp/node_modules/redis/index.js:106:14)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
2018-09-11 13:10:18 [Master]    [Website] Website process died, spawning replacement...

```

**Comment by paintballrefjosh** [comment]
Did your redis server crash?  Or was it ever running?
