### ISSUE TITLE
node-watch 0.6.0 Causes startup error

### ISSUE THREAD

**Issue by garceri** [zone117x/node-open-mining-portal#651]
node-watch [https://www.npmjs.com/package/node-watch](url) Has been recently updated to v6.0.0

It causes an startup error in nomp 

```
# node init.js

/root/optiminer/nomp/node_modules/node-watch/lib/watch.js:110
function getSubDirectories(dir, fn, done = function() {}) {
                                         ^
SyntaxError: Unexpected token =
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/optiminer/nomp/libs/website.js:6:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

```

This is resolved by downgrading node-watch to 0.5.9

```
# npm install node-watch@0.5.9
npm http GET https://registry.npmjs.org/node-watch/0.5.9
npm http 200 https://registry.npmjs.org/node-watch/0.5.9
npm http GET https://registry.npmjs.org/node-watch/-/node-watch-0.5.9.tgz
npm http 200 https://registry.npmjs.org/node-watch/-/node-watch-0.5.9.tgz
node-watch@0.5.9 node_modules/node-watch

```
After this nomp starts just fine..

**Comment by Tr0j4n9** [comment]
I noticed that, I have created a pull request for it

**Comment by zone117x** [comment]
Merged the PR.
Thanks everyone for getting this fixed.
