### ISSUE TITLE
gyp ERR! build error

### ISSUE THREAD

**Issue by thepcb** [zone117x/node-open-mining-portal#655]
Hot to fix this issue?

gyp ERR! build error
gyp ERR! stack Error: make failed with exit code: 2
gyp ERR! stack at ChildProcess.onExit (/root/.nvm/v0.10.47/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack at ChildProcess.emit (events.js:98:17)
gyp ERR! stack at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.16.0-25-generic
gyp ERR! command "node" "/root/.nvm/v0.10.47/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/nomp/node_modules/stratum-pool/node_modules/multi-hashing
gyp ERR! node -v v0.10.47
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm ERR! Linux 3.16.0-25-generic
npm ERR! argv "/root/.nvm/v0.10.47/bin/node" "/root/.nvm/v0.10.47/bin/npm" "update" "--recursive"
npm ERR! node v0.10.47
npm ERR! npm v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! multi-hashing@0.0.9 install: node-gyp rebuild
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the multi-hashing@0.0.9 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the multi-hashing package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR! npm bugs multi-hashing
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR! npm owner ls multi-hashing
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR! /root/nomp/npm-debug.log

Im already tested rm -rf node_module && ../.node-gyp && npm update
Tested with nodejs 0.10.74, 0.10.48, 8.0.0, 10.0.0 and 11.0.0
All versions print same error message.

**Comment by bleach86** [comment]
try installing this package.

sudo apt install libgmp3-dev
