### ISSUE TITLE
bech32 pool address (dev branch)

### ISSUE THREAD

**Issue by cryptozeny** [zone117x/node-open-mining-portal#665]
litecoin
```
{
    "name": "Litecoin",
    "symbol": "LTC",
    "algorithm": "scrypt",
    "peerMagic": "fbc0b6db",
    "peerMagicTestnet": "fdd2c8f1" 
}
```

pool_config
```
    "address": "tltc1qaa8xp4wtnhcl9zhqtwfm4m73d22regyr7tz6d6",
```

but failed. but legacy is ok.

=======

`Error: Non-base58 character`
```
2019-06-28 11:16:04 [Switching]	[Setup] (Thread 4) Loading last proxy state from redis
2019-06-28 11:16:04 [Pool]	[litecoin] (Thread 4) Share processing setup with redis (127.0.0.1:6379)
/home/ak/git/SUGAR/NOMP-REBOOT/nompkawa/node_modules/base-x/index.js:142
    throw new Error('Non-base' + BASE + ' character')
    ^

Error: Non-base58 character
    at Object.decode (/home/ak/git/SUGAR/NOMP-REBOOT/nompkawa/node_modules/base-x/index.js:142:11)
    at Object.decode (/home/ak/git/SUGAR/NOMP-REBOOT/nompkawa/node_modules/bs58check/base.js:39:25)
    at Object.fromBase58Check (/home/ak/git/SUGAR/NOMP-REBOOT/nompkawa/node_modules/bitcoinjs-lib/src/address.js:11:29)
    at Object.exports.addressToScript (/home/ak/git/SUGAR/NOMP-REBOOT/nompkawa/node_modules/stratum-pool/lib/util.js:270:79)
    at /home/ak/git/SUGAR/NOMP-REBOOT/nompkawa/node_modules/stratum-pool/lib/pool.js:444:37
    at /home/ak/git/SUGAR/NOMP-REBOOT/nompkawa/node_modules/stratum-pool/lib/pool.js:446:15
    at /home/ak/git/SUGAR/NOMP-REBOOT/nompkawa/node_modules/stratum-pool/lib/daemon.js:134:13
    at parseJson (/home/ak/git/SUGAR/NOMP-REBOOT/nompkawa/node_modules/stratum-pool/lib/daemon.js:85:17)
    at IncomingMessage.<anonymous> (/home/ak/git/SUGAR/NOMP-REBOOT/nompkawa/node_modules/stratum-pool/lib/daemon.js:95:17)
    at emitNone (events.js:111:20)
2019-06-28 11:16:04 [Master]	[PoolSpawner] Fork 3 died, spawning replacement worker...
```

**Comment by cryptozeny** [comment]
fixed https://github.com/zone117x/node-open-mining-portal/pull/667/files
