### ISSUE TITLE
Website doesn't work with bech32 address

### ISSUE THREAD

**Issue by nachunjae** [zone117x/node-open-mining-portal#666]
@HashUnlimited

Here is the log

```2019-06-29 12:04:56 [Website]   [Server] Website started on 0.0.0.0:8080
/home/ubuntu/node-open-mining-portal/node_modules/bignum/index.js:97
      throw new TypeError('Unspecified operation for type ' +
      ^

TypeError: Unspecified operation for type undefined for add
    at BigNum.(anonymous function) [as add] (/home/ubuntu/node-open-mining-portal/node_modules/bignum/index.js:97:13)
    at Object.decode (/home/ubuntu/node-open-mining-portal/node_modules/base58-native/base58.js:49:23)
    at Object.exports.getVersionByte (/home/ubuntu/node-open-mining-portal/node_modules/stratum-pool/lib/util.js:23:30)
    at /home/ubuntu/node-open-mining-portal/libs/website.js:170:45
    at /home/ubuntu/node-open-mining-portal/node_modules/stratum-pool/lib/daemon.js:175:17
    at /home/ubuntu/node-open-mining-portal/node_modules/async/lib/async.js:52:16
    at done (/home/ubuntu/node-open-mining-portal/node_modules/async/lib/async.js:246:17)
    at /home/ubuntu/node-open-mining-portal/node_modules/async/lib/async.js:44:16
    at itemFinished (/home/ubuntu/node-open-mining-portal/node_modules/stratum-pool/lib/daemon.js:158:17)
    at /home/ubuntu/node-open-mining-portal/node_modules/stratum-pool/lib/daemon.js:169:17
2019-06-29 12:04:56 [Master]    [Website] Website process died, spawning replacement...
2019-06-29 12:04:56 [Payments]  [litecoin] Finished interval - time spent: 7ms total, 3ms redis, 3ms daemon RPC
```

Using litecoin testnet, with config

```
diff --git a/coins/litecoin.json b/coins/litecoin.json
index 33d5d55..de43d10 100644
--- a/coins/litecoin.json
+++ b/coins/litecoin.json
@@ -3,5 +3,23 @@
     "symbol": "LTC",
     "algorithm": "scrypt",
     "peerMagic": "fbc0b6db",
-    "peerMagicTestnet": "fdd2c8f1"
+    "peerMagicTestnet": "fdd2c8f1",
+
+    "mainnet": {
+      "bech32": "ltc",
+      "bip32": {
+        "public": "0488B21E"
+      },
+      "pubKeyHash": "30",
+      "scriptHash": "05"
+    },
+
+    "testnet": {
+      "bech32": "tltc",
+      "bip32": {
+        "public": "043587CF"
+      },
+      "pubKeyHash": "6F",
+      "scriptHash": "C4"
+    }
 }
```

**Comment by cryptozeny** [comment]
same here

**Comment by knkrth** [comment]
I got this error while using the latest bitcoin version v0.19

**Comment by Leonardiae** [comment]
Same here. Get this error with bech address, when I use a native address it works.
