### ISSUE TITLE
Bitcoin Core 0.21 issue.. 

### ISSUE THREAD

**Issue by Sany-IO** [zone117x/node-open-mining-portal#701]
Hello,

I added a new bitcoin pool with Bitcoin Core 0.21, now is start the init.js  and there gives a error:

`root@ubuntu~/nomp# nodejs init.js
2021-04-06 23:01:14 [POSIX]	[Connection Limit] (Safe to ignore) POSIX module not installed and resource (connection) limit was not raised
2021-04-06 23:01:14 [Master]	[CLI] CLI listening on port 17117
2021-04-06 23:01:14 [Website]	[Server] Website started on xxxxx:81
2021-04-06 23:01:14 [Master]	[PoolSpawner] Spawned 1 pool(s) on 2 thread(s)
/root/nomp/node_modules/bignum/index.js:97
      throw new TypeError('Unspecified operation for type ' +
      ^

TypeError: Unspecified operation for type undefined for add
    at BigNum.(anonymous function) [as add] (/root/nomp/node_modules/bignum/index.js:97:13)
    at Object.decode (/root/nomp/node_modules/base58-native/base58.js:49:23)
    at Object.exports.getVersionByte (/root/nomp/node_modules/stratum-pool/lib/util.js:22:30)
    at /root/nomp/libs/website.js:170:45
    at /root/nomp/node_modules/stratum-pool/lib/daemon.js:175:17
    at /root/nomp/node_modules/async/lib/async.js:52:16
    at done (/root/nomp/node_modules/async/lib/async.js:246:17)
    at /root/nomp/node_modules/async/lib/async.js:44:16
    at itemFinished (/root/nomp/node_modules/stratum-pool/lib/daemon.js:158:17)
    at /root/nomp/node_modules/stratum-pool/lib/daemon.js:169:17
2021-04-06 23:01:14 [Master]	[Website] Website process died, spawning replacement...
2021-04-06 23:01:15 [Payments]	[bitcoin] Payment processing setup to run every 120 second(s) with daemon (XXX:19332) and redis (127.0.0.1:6379)
2021-04-06 23:01:15 [Payments]	[bitcoin] Finished interval - time spent: 56ms total, 3ms redis, 54ms daemon RPC
2021-04-06 23:01:15 [Switching]	[Setup] (Thread 1) Loading last proxy state from redis
2021-04-06 23:01:15 [Switching]	[Setup] (Thread 2) Loading last proxy state from redis
/root/nomp/node_modules/bignum/index.js:97
      throw new TypeError('Unspecified operation for type ' +
      ^

TypeError: Unspecified operation for type undefined for add
    at BigNum.(anonymous function) [as add] (/root/nomp/node_modules/bignum/index.js:97:13)
    at Object.decode (/root/nomp/node_modules/base58-native/base58.js:49:23)
    at Object.exports.addressToScript (/root/nomp/node_modules/stratum-pool/lib/util.js:266:26)
    at /root/nomp/node_modules/stratum-pool/lib/pool.js:426:37
    at /root/nomp/node_modules/stratum-pool/lib/pool.js:428:15
    at /root/nomp/node_modules/stratum-pool/lib/daemon.js:134:13
    at parseJson (/root/nomp/node_modules/stratum-pool/lib/daemon.js:85:17)
    at IncomingMessage.<anonymous> (/root/nomp/node_modules/stratum-pool/lib/daemon.js:95:17)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
2021-04-06 23:01:15 [Master]	[PoolSpawner] Fork 0 died, spawning replacement worker...
/root/nomp/node_modules/bignum/index.js:97
      throw new TypeError('Unspecified operation for type ' +
      ^

TypeError: Unspecified operation for type undefined for add
    at BigNum.(anonymous function) [as add] (/root/nomp/node_modules/bignum/index.js:97:13)
    at Object.decode (/root/nomp/node_modules/base58-native/base58.js:49:23)
    at Object.exports.addressToScript (/root/nomp/node_modules/stratum-pool/lib/util.js:266:26)
    at /root/nomp/node_modules/stratum-pool/lib/pool.js:426:37
    at /root/nomp/node_modules/stratum-pool/lib/pool.js:428:15
    at /root/nomp/node_modules/stratum-pool/lib/daemon.js:134:13
    at parseJson (/root/nomp/node_modules/stratum-pool/lib/daemon.js:85:17)
    at IncomingMessage.<anonymous> (/root/nomp/node_modules/stratum-pool/lib/daemon.js:95:17)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
2021-04-06 23:01:15 [Master]	[PoolSpawner] Fork 1 died, spawning replacement worker...
^C`

now i disable the bitcoin.json configuration, there are works fine....

is there any fix?

**Comment by Sany-IO** [comment]
Hello,

okay, i fixed this Problem, the problem with the new BitCoin Core is, that are generates bech32 Walletaddresses, the node Library base58 is not usable for this addresses.

i generated a new wallet address with this command, and it works:
'bitcoin-cli getnewaddress "label" "p2sh-segwit"'
