### ISSUE TITLE
init.js ESMLoader  -- ECMAScript module loader -- Node 18; NPM 8.6.0; Bent; Ubuntu 20.04.04

### ISSUE THREAD

**Issue by jdawg24** [zone117x/node-open-mining-portal#721]
getting the following output when running node init.js from nomp repo on ubuntu server 20.04.04 :

file:///home/user/nomp/init.js:22
    return;
    ^^^^^^

SyntaxError: Illegal return statement
    at ESMLoader.moduleStrategy (node:internal/modules/esm/translators:117:18)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:361:14)
    at async link (node:internal/modules/esm/module_job:70:21)

Node.js v18.0.0

I've tweaked the dependencies on package.json to substitute bent for request (now deprecated) but gather this issue is mainly to do with ECMA scripts from > node version 14. Since Glib has be uprated with latest version of node deprecating ubuntu 18, focal fossa probable route forward.

**Comment by jdawg24** [comment]
changing "type": "modules" to  "type": "commonjs" in package.json outputs:

op@nomp:~/nomp$ node init.js
/home/op/nomp/libs/logUtil.js:1
var dateFormat = require('dateformat');
                 ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /home/op/nomp/node_modules/                                     dateformat/lib/dateformat.js from /home/op/nomp/libs/logUtil.js not support                                     ed.
Instead change the require of dateformat.js in /home/op/nomp/libs/logUtil.j                                     s to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/home/op/nomp/libs/logUtil.js:1:18)
    at Object.<anonymous> (/home/op/nomp/init.js:9:18) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v18.0.0


currently leafing through https://nodejs.org/api/modules.html
