### ISSUE TITLE
Raspberry pi ARM 64 bit ubuntu 18.04 installation fail

### ISSUE THREAD

**Issue by free1video** [zone117x/node-open-mining-portal#725]
ubuntu@ubuntu:~/nomp$ npm install  multi-hashing

> multi-hashing@1.0.2 install /home/ubuntu/nomp/node_modules/multi-hashing
> node-gyp rebuild

gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack TypeError: Object.fromEntries is not a function
gyp ERR! stack     at Object.<anonymous> (/home/ubuntu/.nvm/versions/node/v12.14.0/lib/node_modules/node-gyp/node_modules/@npmcli/fs/lib/fs.js:6:23)
gyp ERR! stack     at Module._compile (module.js:652:30)
gyp ERR! stack     at Object.Module._extensions..js (module.js:663:10)
gyp ERR! stack     at Module.load (module.js:565:32)
gyp ERR! stack     at tryModuleLoad (module.js:505:12)
gyp ERR! stack     at Function.Module._load (module.js:497:3)
gyp ERR! stack     at Module.require (module.js:596:17)
gyp ERR! stack     at require (internal/module.js:11:18)
gyp ERR! stack     at Object.<anonymous> (/home/ubuntu/.nvm/versions/node/v12.14.0/lib/node_modules/node-gyp/node_modules/@npmcli/fs/lib/index.js:2:6)
gyp ERR! stack     at Module._compile (module.js:652:30)
gyp ERR! System Linux 5.4.0-1068-raspi
gyp ERR! command "/usr/bin/node" "/home/ubuntu/.nvm/versions/node/v12.14.0/lib/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ubuntu/nomp/node_modules/multi-hashing
gyp ERR! node -v v8.10.0
gyp ERR! node-gyp -v v9.1.0
gyp ERR! Node-gyp failed to build your package.
gyp ERR! Try to update npm and/or node-gyp and if it does not help file an issue with the package author.
npm ERR! Linux 5.4.0-1068-raspi
npm ERR! argv "/usr/bin/node" "/usr/local/bin/npm" "install" "multi-hashing"
npm ERR! node v8.10.0
npm ERR! npm  v3.7.3
npm ERR! code ELIFECYCLE

npm ERR! multi-hashing@1.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the multi-hashing@1.0.2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the multi-hashing package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs multi-hashing
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls multi-hashing
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/nomp/npm-debug.log
ubuntu@ubuntu:~/nomp$ sudo npm update

> multi-hashing@1.0.3 install /home/ubuntu/nomp/node_modules/multi-hashing
> node-gyp rebuild

gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack TypeError: Object.fromEntries is not a function
gyp ERR! stack     at Object.<anonymous> (/home/ubuntu/.nvm/versions/node/v12.14.0/lib/node_modules/node-gyp/node_modules/@npmcli/fs/lib/fs.js:6:23)
gyp ERR! stack     at Module._compile (module.js:652:30)
gyp ERR! stack     at Object.Module._extensions..js (module.js:663:10)
gyp ERR! stack     at Module.load (module.js:565:32)
gyp ERR! stack     at tryModuleLoad (module.js:505:12)
gyp ERR! stack     at Function.Module._load (module.js:497:3)
gyp ERR! stack     at Module.require (module.js:596:17)
gyp ERR! stack     at require (internal/module.js:11:18)
gyp ERR! stack     at Object.<anonymous> (/home/ubuntu/.nvm/versions/node/v12.14.0/lib/node_modules/node-gyp/node_modules/@npmcli/fs/lib/index.js:2:6)
gyp ERR! stack     at Module._compile (module.js:652:30)
gyp ERR! System Linux 5.4.0-1068-raspi
gyp ERR! command "/usr/bin/node" "/home/ubuntu/.nvm/versions/node/v12.14.0/lib/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ubuntu/nomp/node_modules/multi-hashing
gyp ERR! node -v v8.10.0
gyp ERR! node-gyp -v v9.1.0
gyp ERR! Node-gyp failed to build your package.
gyp ERR! Try to update npm and/or node-gyp and if it does not help file an issue with the package author.
npm ERR! Linux 5.4.0-1068-raspi
npm ERR! argv "/usr/bin/node" "/usr/local/bin/npm" "update"
npm ERR! node v8.10.0
npm ERR! npm  v3.7.3
npm ERR! code ELIFECYCLE

npm ERR! multi-hashing@1.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the multi-hashing@1.0.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the multi-hashing package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs multi-hashing
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls multi-hashing
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/nomp/npm-debug.log
ubuntu@ubuntu:~/nomp$

**Comment by free1video** [comment]
ubuntu@ubuntu:~/nomp$ sudo npm update
npm WARN deprecated request@2.69.0: request has been deprecated, see https://git                                                                  hub.com/request/request/issues/3142
npm WARN deprecated har-validator@2.0.6: this library is no longer supported
npm WARN deprecated hawk@3.1.3: This module moved to @hapi/hawk. Please make sure to switch o                                                     ver as this distribution is no longer supported and may contain bugs and critical security is                                                     sues.
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodese                                                     curity.io/advisories/130
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated boom@2.10.1: This version has been deprecated in accordance with the hapi                                                      support policy (hapi.im/support). Please upgrade to the latest version to get the best featu                                                     res, bug fixes, and security patches. If you are unable to upgrade at this time, paid support                                                      is available for older versions (hapi.im/commercial).
npm WARN deprecated cryptiles@2.0.5: This version has been deprecated in accordance with the                                                      hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best f                                                     eatures, bug fixes, and security patches. If you are unable to upgrade at this time, paid sup                                                     port is available for older versions (hapi.im/commercial).
npm WARN deprecated sntp@1.0.9: This module moved to @hapi/sntp. Please make sure to switch o                                                     ver as this distribution is no longer supported and may contain bugs and critical security is                                                     sues.
npm WARN deprecated hoek@2.16.3: This version has been deprecated in accordance with the hapi                                                      support policy (hapi.im/support). Please upgrade to the latest version to get the best featu                                                     res, bug fixes, and security patches. If you are unable to upgrade at this time, paid support                                                      is available for older versions (hapi.im/commercial).

> multi-hashing@1.0.2 install /home/ubuntu/nomp/node_modules/multi-hashing
> node-gyp rebuild

gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack TypeError: Object.fromEntries is not a function
gyp ERR! stack     at Object.<anonymous> (/home/ubuntu/.nvm/versions/node/v12.14.0/lib/node_modules/node-gyp/node_modules/@npmcli/fs/lib/fs.js:6:23)
gyp ERR! stack     at Module._compile (module.js:653:30)
gyp ERR! stack     at Object.Module._extensions..js (module.js:664:10)
gyp ERR! stack     at Module.load (module.js:566:32)
gyp ERR! stack     at tryModuleLoad (module.js:506:12)
gyp ERR! stack     at Function.Module._load (module.js:498:3)
gyp ERR! stack     at Module.require (module.js:597:17)
gyp ERR! stack     at require (internal/module.js:11:18)
gyp ERR! stack     at Object.<anonymous> (/home/ubuntu/.nvm/versions/node/v12.14.0/lib/node_modules/node-gyp/node_modules/@npmcli/fs/lib/index.js:2:6)
gyp ERR! stack     at Module._compile (module.js:653:30)
gyp ERR! System Linux 5.4.0-1068-raspi
gyp ERR! command "/usr/bin/node" "/home/ubuntu/.nvm/versions/node/v12.14.0/lib/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ubuntu/nomp/node_modules/multi-hashing
gyp ERR! node -v v8.17.0
gyp ERR! node-gyp -v v9.1.0
gyp ERR! Node-gyp failed to build your package.
gyp ERR! Try to update npm and/or node-gyp and if it does not help file an issue with the package author.
node-open-mining-portal@0.0.4 /home/ubuntu/nomp
├── async@1.5.2
├── base58-native@0.1.4  extraneous
├── bignum@0.13.1
├── body-parser@1.20.0
├── colors@1.4.0
├── compression@1.7.4
├── dateformat@1.0.12
├── dot@1.1.3
├── express@4.18.1
├── extend@3.0.2
├── mysql@2.18.1
├── node-json-minify@3.0.0
├── node-watch@0.5.9
├── nonce@1.0.4
├── redis@0.12.1
└── request@2.69.0

npm ERR! Linux 5.4.0-1068-raspi
npm ERR! argv "/usr/bin/node" "/usr/local/bin/npm" "update"
npm ERR! node v8.17.0
npm ERR! npm  v3.7.3
npm ERR! code ELIFECYCLE

npm ERR! multi-hashing@1.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the multi-hashing@1.0.2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the multi-hashing package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs multi-hashing
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls multi-hashing
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/nomp/npm-debug.log
