### ISSUE TITLE
what does this error mean

### ISSUE THREAD

**Issue by arzzen** [zone117x/node-open-mining-portal#99]
I've got the following error message after I installed the mining pool

root@root:/home/nomp# node init.js
2014-04-28 17:57:20 [POSIX] [Connection Limit](Safe to ignore) POSIX module not installed and resource (connection) limit was not raised
2014-04-28 17:57:20 [Master]    [Blocknotify] Blocknotify listener disabled
2014-04-28 17:57:20 [Master]    [Coinswitch] Coinswitch listener disabled
2014-04-28 17:57:21 [Payments]  [GlobalDenomination] Payment processing setup to run every 20 second(s) with daemon (mngr@127.0.0.1:38347) and redis (127.0.0.1:6379)
2014-04-28 17:57:21 [Payments]  [GlobalDenomination] [Took 2ms] Check finished - no pending blocks in redis
2014-04-28 17:57:21 [Proxy] [Setup](Thread 1) Loading last proxy state from redis
2014-04-28 17:57:21 [MySQL] [GlobalDenomination] Successful connection to MySQL database
2014-04-28 17:57:21 [Pool]  [GlobalDenomination](Thread 1) getblocktemplate call failed for daemon instance 1 with error {"type":"offline","message":"connect ECONNREFUSED"}
2014-04-28 17:57:21 [Pool]  [GlobalDenomination](Thread 1) Error with getblocktemplate on creating first job, server cannot start
2014-04-28 17:57:21 [Pool]  [GlobalDenomination](Thread 1) Network diff of 15.45020458 is lower than port 3256 w/ diff 256 and port 3789 w/ diff 16

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: bind EADDRINUSE
    at errnoException (net.js:904:11)
    at net.js:1084:30
    at Object.2:1 (cluster.js:592:5)
    at handleResponse (cluster.js:171:41)
    at respond (cluster.js:192:5)
    at handleMessage (cluster.js:202:5)
    at process.EventEmitter.emit (events.js:117:20)
    at handleMessage (child_process.js:318:10)
    at child_process.js:392:7
    at process.handleConversion.net.Native.got (child_process.js:91:7)
2014-04-28 17:57:21 [Master]    [PoolSpanwer] Fork 0 died, spawning replacement worker...
2014-04-28 17:57:21 [Proxy] [Setup](Thread 2) Loading last proxy state from redis
2014-04-28 17:57:21 [MySQL] [GlobalDenomination] Successful connection to MySQL database
2014-04-28 17:57:21 [Pool]  [GlobalDenomination](Thread 2) getblocktemplate call failed for daemon instance 1 with error {"type":"offline","message":"connect ECONNREFUSED"}
2014-04-28 17:57:21 [Pool]  [GlobalDenomination](Thread 2) Error with getblocktemplate on creating first job, server cannot start

**Comment by erm3nda** [comment]
The problem is clear. Address in use, surely you did started the daemon previosly and you cannot start it again. U should look for it into processes list then send SIGTERM or SIGKILL if goes hardcore. Some coins daemon works better than others, so don't expect always the same behavior. Learn to read what the message says, in this case `Error: bind EADDRINUSE` that produces finally `ECONNREFUSED` that means by the way that can't connect because port, or daemon not running. Maybe you did apply changes to first daemon or it's unomp config, so didnt match. Restart daemon and everything should be ok.

If you make changes only to the coin config you can reload it using `nodejs /scripts/cli.js reloadpool coinname`.
